%
% Parameters to do stimulus triggered averaging of the EMG
%
%       function sta_params = stim_trig_avg_default()
%
%       stim_trig_avg_params    : structure with fields
%           stim_elec           : the electrode that will be stimulated
%           stim_ampl           : stimulation amplitude (mA)
%           stim_pw             : stimulation pulse width (ms)
%           stim_freq           : stimulation frequency (Hz)
%           nbr_stims_ch        : nbr stimuli that will be delivered 
%           t_before            : time before the stim that is plotted and used for computations (ms)
%           t_after             : time after the stim that is plotted and used for computations (ms)
%           record_force_yn     : record force and do the FTA (bool)
%           save_data_yn        : save Matlab and Cerebus data (bool)
%           plot_yn             : plot the results (bool)
%           sync_out_elec       : sync out electrode number (to sync with cerebus)
%           stimulator_resolut  : step size (mA)
%           data_dir            : directory where the data will be saved
%           monkey              : monkey name, to generate the filename
%           task                : task name, to generate the filename
%



function sta_params = stim_trig_avg_default3()


sta_params              = struct( ...
    'stim_elec',                1, ...
    'stim_ampl',                0.054, ...%0.054, ...
    'stim_pw',                  0.2, ...
    'stim_freq',                15, ...
    'nbr_stims_ch',             1500, ...
    't_before',                 20, ...
    't_after',                  30, ...
    'record_emg_yn',            true, ...
    'record_force_yn',          false, ...
    'save_data_yn',             true, ...
    'plot_yn',                  true, ...
    'sync_out_elec',            32, ...
    'stimulator_resolut',       0.018, ...
    'data_dir',                 'E:\Data-lab1\12A1-Jango\CerebusData\TDCS', ...
    'monkey',                   'Jango', ...
    'bank',                     'A', ...
    'task',                     'WF');
