function plotHists()
clear;
close all;

baseDir = 'Z:\MrT_9I4\Matt\ProcessedData';
outDir = 'C:\Users\Matt Perich\Dropbox\tcmc_talk\figure_report';
usePeriod = 'initial';
useArray = 'PMd';

binSize = 5;

cssLoc = fullfile(outDir,'mainstyle.css');
html = ['<html><head><title>DATA!</title><link rel="stylesheet" href="' cssLoc '" /></head><body>'];

% quick table of contents
lnks = {'VRem_VRlm', ...
 'FFem_FFlm', ...
 'FFlm_VRlm', ...
 'VRlm_VRlt', ...
 'FFlm_FFlt', ...
 'VRFFem_VRFFlm', ...
 'VRFFlm_VRFFlt', ...
 'VRlm_VRFFlm', ...
 'FFlm_VRFFlm'};

for i = 1:length(lnks)
    html = strcat(html,['<a href="#' lnks{i} '">' lnks{i} '</a><br>']);
end

html = strcat(html,'<br><br>');

% plotPDShiftCellClasses('dir',baseDir,'dates',useDates,'period',usePeriod,'array',useArray)
% cell matrix. each row is a file to add to plots. each column is info:
%   {'recording_date','adaptation','task','parameter_set_name','title of file'}

% 1) Compare VR movement early and VR movement late
n = 'VRem_VRlm';
useDates = {'2013-09-04','VR','RT','early','VR-early'; ...
    '2013-09-06','VR','RT','early','VR-early'; ...
    '2013-09-10','VR','RT','early','VR-early'; ...
    '2013-09-04','VR','RT','late','VR-late'; ...
    '2013-09-06','VR','RT','late','VR-late'; ...
    '2013-09-10','VR','RT','late','VR-late'};
plotPDShiftComparisonHistograms('dir',baseDir,'dates',useDates,'period',usePeriod,'array',useArray,'binsize',binSize,'savepath',fullfile(outDir,n))
t = 'VR early and VR late';
html = addReportNode(html,n,t,outDir);

% 2) Compare FF movement early and FF movement late
n = 'FFem_FFlm';
useDates = {'2013-08-20','FF','RT','early','FF-early'; ...
    '2013-08-22','FF','RT','early','FF-early'; ...
    '2013-08-30','FF','RT','early','FF-early'; ...
    '2013-08-20','FF','RT','late','FF-late'; ...
    '2013-08-22','FF','RT','late','FF-late'; ...
    '2013-08-30','FF','RT','late','FF-late'};
plotPDShiftComparisonHistograms('dir',baseDir,'dates',useDates,'period',usePeriod,'array',useArray,'binsize',binSize,'savepath',fullfile(outDir,n))
t = 'FF early and FF late';
html = addReportNode(html,n,t,outDir);

% 3) Compare FF movement and VR movement
n = 'FFlm_VRlm';
useDates = {'2013-08-20','FF','RT','late','FF-move'; ...
    '2013-08-22','FF','RT','late','FF-move'; ...
    '2013-08-30','FF','RT','late','FF-move'; ...
    '2013-09-04','VR','RT','late','VR-move'; ...
    '2013-09-06','VR','RT','late','VR-move'; ...
    '2013-09-10','VR','RT','late','VR-move'};
plotPDShiftComparisonHistograms('dir',baseDir,'dates',useDates,'period',usePeriod,'array',useArray,'binsize',binSize,'savepath',fullfile(outDir,n))
t = 'FF and VR movement';
html = addReportNode(html,n,t,outDir);

% 4) Compare VR movement and VR target
n = 'VRlm_VRlt';
useDates = {'2013-09-04','VR','RT','late','VR-move'; ...
    '2013-09-06','VR','RT','late','VR-move'; ...
    '2013-09-10','VR','RT','late','VR-move'; ...
    '2013-09-04','VR','RT','targlate','VR-targ'; ...
    '2013-09-06','VR','RT','targlate','VR-targ'; ...
    '2013-09-10','VR','RT','targlate','VR-targ'};
plotPDShiftComparisonHistograms('dir',baseDir,'dates',useDates,'period',usePeriod,'array',useArray,'binsize',binSize,'savepath',fullfile(outDir,n))
t = 'VR movement and VR target';
html = addReportNode(html,n,t,outDir);

% 5) Compare FF movement and FF target
n = 'FFlm_FFlt';
useDates = {'2013-08-20','FF','RT','late','FF-move'; ...
    '2013-08-22','FF','RT','late','FF-move'; ...
    '2013-08-30','FF','RT','late','FF-move'; ...
    '2013-08-20','FF','RT','targlate','FF-targ'; ...
    '2013-08-22','FF','RT','targlate','FF-targ'; ...
    '2013-08-30','FF','RT','targlate','FF-targ'};
plotPDShiftComparisonHistograms('dir',baseDir,'dates',useDates,'period',usePeriod,'array',useArray,'binsize',binSize,'savepath',fullfile(outDir,n))
t = 'FF movement and FF target';
html = addReportNode(html,n,t,outDir);

% 6) Compare VRFF early and VRFF late
n = 'VRFFem_VRFFlm';
useDates = {'2013-09-24','VRFF','RT','early','VRFF-early'; ...
    '2013-09-25','VRFF','RT','early','VRFF-early'; ...
    '2013-09-27','VRFF','RT','early','VRFF-early'; ...
    '2013-09-24','VRFF','RT','late','VRFF-late'; ...
    '2013-09-25','VRFF','RT','late','VRFF-late'; ...
    '2013-09-27','VRFF','RT','late','VRFF-late'};
plotPDShiftComparisonHistograms('dir',baseDir,'dates',useDates,'period',usePeriod,'array',useArray,'binsize',binSize,'savepath',fullfile(outDir,n))
t = 'VRFF early and VRFF late';
html = addReportNode(html,n,t,outDir);

% 7) Compare VRFF movement and VRFF target
n = 'VRFFlm_VRFFlt';
useDates = {'2013-09-24','VRFF','RT','late','VRFF-move'; ...
    '2013-09-25','VRFF','RT','late','VRFF-move'; ...
    '2013-09-27','VRFF','RT','late','VRFF-move'; ...
    '2013-09-24','VRFF','RT','targlate','VRFF-targ'; ...
    '2013-09-25','VRFF','RT','targlate','VRFF-targ'; ...
    '2013-09-27','VRFF','RT','targlate','VRFF-targ'};
plotPDShiftComparisonHistograms('dir',baseDir,'dates',useDates,'period',usePeriod,'array',useArray,'binsize',binSize,'savepath',fullfile(outDir,n))
t = 'VRFF movement and VRFF target';
html = addReportNode(html,n,t,outDir);

% 8) Compare VR movement and VRFF movement
n = 'VRlm_VRFFlm';
useDates = {'2013-09-04','VR','RT','late','VR-move'; ...
    '2013-09-06','VR','RT','late','VR-move'; ...
    '2013-09-10','VR','RT','late','VR-move'; ...
    '2013-09-24','VRFF','RT','late','VRFF-move'; ...
    '2013-09-25','VRFF','RT','late','VRFF-move'; ...
    '2013-09-27','VRFF','RT','late','VRFF-move'};
plotPDShiftComparisonHistograms('dir',baseDir,'dates',useDates,'period',usePeriod,'array',useArray,'binsize',binSize,'savepath',fullfile(outDir,n))
t = 'VR and VRFF movement';
html = addReportNode(html,n,t,outDir);

% 9) Compare FF movement and VRFF movement
n = 'FFlm_VRFFlm';
useDates = {'2013-08-20','FF','RT','late','FF-move'; ...
    '2013-08-22','FF','RT','late','FF-move'; ...
    '2013-08-30','FF','RT','late','FF-move'; ...
    '2013-09-24','VRFF','RT','late','VRFF-move'; ...
    '2013-09-25','VRFF','RT','late','VRFF-move'; ...
    '2013-09-27','VRFF','RT','late','VRFF-move'};
plotPDShiftComparisonHistograms('dir',baseDir,'dates',useDates,'period',usePeriod,'array',useArray,'binsize',binSize,'savepath',fullfile(outDir,n))
t = 'FF and VRFF movement';
html = addReportNode(html,n,t,outDir);

close all;

% make a quick report
html = strcat(html,'</body></html>');

fn = fullfile(outDir,'report.html');
fid = fopen(fn,'w+');
fprintf(fid,'%s',html);
fclose(fid);


end

function html = addReportNode(html,name,title,outDir)

imgWidth = 600;

html = strcat(html,['<div id="' name '">' title '<br><table><tr>' ...
    '<td><img src="' fullfile(outDir,[name '_ad.png']) '" width="' num2str(imgWidth) '"></td>' ...
    '<td><img src="' fullfile(outDir,[name '_bar.png']) '" width="' num2str(imgWidth) '"></td>' ...
    '<td><img src="' fullfile(outDir,[name '_wo.png']) '" width="' num2str(imgWidth) '"></td>' ...
    '</tr></table></div><br>']);
end


