function [Zstruct] = read_array_impedances(varargin)
%   [Zstruct] = read_array_impedances(varargin)
%   
%   Import impedances from a .txt file as generated by Cerebus into a
%   Matlab structure
%
%   Zstruct:    
%       |----> Info: cell array of info extracted from file header
%       |----> Z   : 96x1 vector of impedances values in KOhms
%
%   varargin:   file path and name as char array.
%               If not provided, will prompt user.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Zstruct=[];

if nargin > 1
    disp('Invalid number of argument');
    return;
elseif nargin
    filename = varargin{1};
    if ~ischar(filename)
        disp('Invalid argument');
        return;
    end
else
    [filename, filepath] = uigetfile('*.txt','Please choose the impedance .txt file');
    filename = [filepath filename];
end

fid = fopen(filename);
if fid<0
    disp('Could not find that file');
    return;
end

%Read Header
% could have used fstrvcat
infolines = cell(9,1);
line_idx = [];
line_len = zeros(9,1);
for i = 1:9
    infolines{i} = strrep(fgetl(fid),'*','');
    line_len(i)  = length(infolines{i});
    if line_len(i) > 0
        line_idx = [line_idx i];
    end
end

numlines = length(line_idx);
info = char(zeros(numlines,max(line_len)));
for i = 1:numlines
    info(i,1:line_len(line_idx(i))) = infolines{line_idx(i)};
end     

%Read Impedances
Z = -1*ones(96,1);
for i = 1:96
    tmptxt = fgetl(fid);
    %the text is like: ' chanxx   zzz kOhm'
    %                  '123456789012345789'
    %it always have 19 characters, and
    %impedances are between 8 and 14
    Z(i) = str2double(deblank(tmptxt(8:14)));
end

Zstruct = struct('Z',Z,'info',info);

fclose(fid);

