function Jac = calc_jacobian(q, arm_params)

% Angles must be in radians, all other measurements are in meters.
if nargin == 1
    arm_params = read_initialization_file('Monkey_arm_7');
end
alpha = arm_params.Alpha;
pull = arm_params.Pull;
La = arm_params.La;
Lb = arm_params.Lb;
Lc = arm_params.Lc;

Jac(1,1) = 0;

Jac(1,2) = La(3)*cos(q(2)) + Lb(3)*cos(q(2)) + La(2)*sin(q(2))*sin(q(3)) + Lb(2)*sin(q(2))*sin(...
  q(3)+q(4)) + Lc(2)*(sin(alpha)*cos(q(2))+cos(alpha)*sin(q(2))*sin(q(3)+q(4))) + Lc(3)*(cos(...
  alpha)*cos(q(2))*cos(q(5))-sin(q(2))*(cos(q(3))*(sin(q(5))*cos(q(4))+sin(alpha)*sin(q(4))*...
  cos(q(5)))-sin(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(q(5))))) + pull(3)*(...
  cos(q(2))*(sin(alpha)*sin(alpha-q(6))+cos(alpha)*cos(q(5))*cos(alpha-q(6)))+sin(q(2))*(...
  sin(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-...
  sin(alpha)*cos(q(5))*cos(alpha-q(6))))-cos(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-...
  sin(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6)))))) + ...
  pull(1)*(cos(q(2))*(sin(alpha)*sin(q(7))*cos(alpha-q(6))-cos(alpha)*(sin(q(5))*cos(q(7))+...
  sin(q(7))*cos(q(5))*sin(alpha-q(6))))+sin(q(2))*(sin(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-...
  sin(q(5))*sin(q(7))*sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+...
  sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))-cos(q(3))*(cos(...
  q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(...
  q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))) + ...
  pull(2)*(cos(q(2))*(sin(alpha)*cos(q(7))*cos(alpha-q(6))+cos(alpha)*(sin(q(5))*sin(q(7))-...
  cos(q(5))*cos(q(7))*sin(alpha-q(6))))+sin(q(2))*(cos(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+...
  sin(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-...
  sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))-sin(q(3))*(sin(...
  q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(...
  q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))) - ...
  La(1)*sin(q(2))*cos(q(3)) - Lb(1)*sin(q(2))*cos(q(3)+q(4)) - Lc(1)*(cos(alpha)*sin(q(5))*cos(...
  q(2))-sin(q(2))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-cos(q(3))*(...
  cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5)))));
  
Jac(1,3) = -cos(q(2))*(La(1)*sin(q(3))+La(2)*cos(q(3))+Lb(1)*sin(q(3)+q(4))+Lb(2)*cos(q(3)+q(4))+Lc(2)*...
  cos(alpha)*cos(q(3)+q(4))+Lc(1)*(cos(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(...
  q(4)))+sin(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))+Lc(3)*(sin(q(3))*(...
  sin(q(5))*cos(q(4))+sin(alpha)*sin(q(4))*cos(q(5)))+cos(q(3))*(sin(q(4))*sin(q(5))-sin(...
  alpha)*cos(q(4))*cos(q(5))))+pull(3)*(cos(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(...
  q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))+sin(q(3))*(...
  sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*...
  cos(q(5))*cos(alpha-q(6)))))+pull(1)*(cos(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*...
  sin(q(7))*sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(...
  sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))+sin(q(3))*(cos(q(4))*(cos(q(5))*...
  cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(...
  alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))-...
  pull(2)*(sin(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(...
  q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*...
  cos(q(7))*sin(alpha-q(6)))))+cos(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*...
  sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*...
  sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))));
  
Jac(1,4) = -cos(q(2))*(Lb(1)*sin(q(3)+q(4))+Lb(2)*cos(q(3)+q(4))+Lc(2)*cos(alpha)*cos(q(3)+q(4))+...
  Lc(1)*(cos(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))+sin(q(3))*(cos(q(4))*...
  cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))+Lc(3)*(sin(q(3))*(sin(q(5))*cos(q(4))+sin(...
  alpha)*sin(q(4))*cos(q(5)))+cos(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(q(5))))+...
  pull(3)*(cos(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-...
  q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))+sin(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-...
  q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6)))))+...
  pull(1)*(cos(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))+cos(...
  q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*...
  cos(q(5))*sin(alpha-q(6)))))+sin(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*...
  sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*...
  cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))-pull(2)*(sin(q(3))*(cos(q(4))*(sin(q(7))*...
  cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(...
  alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))+cos(...
  q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(...
  alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*...
  sin(alpha-q(6)))))));
  
Jac(1,5) = pull(2)*(cos(alpha)*sin(q(2))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(...
  alpha-q(6)))+cos(q(2))*(cos(q(3))*(cos(q(4))*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(...
  alpha-q(6)))+sin(alpha)*sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6))))-...
  sin(q(3))*(sin(q(4))*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))-sin(alpha)*...
  cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))))) - Lc(1)*(cos(alpha)*...
  sin(q(2))*cos(q(5))+cos(q(2))*(cos(q(3))*(sin(q(5))*cos(q(4))+sin(alpha)*sin(q(4))*cos(q(5)))-...
  sin(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(q(5))))) - Lc(3)*(cos(alpha)*...
  sin(q(2))*sin(q(5))+cos(q(2))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-...
  cos(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))) - pull(3)*cos(alpha-q(6))*(...
  cos(alpha)*sin(q(2))*sin(q(5))+cos(q(2))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(...
  q(5))*cos(q(4)))-cos(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))) - pull(1)*(...
  cos(alpha)*sin(q(2))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))+cos(q(2))*(...
  cos(q(3))*(cos(q(4))*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))+sin(alpha)*...
  sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6))))-sin(q(3))*(sin(q(4))*(...
  sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))-sin(alpha)*cos(q(4))*(cos(q(5))*...
  cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6))))));
  
Jac(1,6) = pull(1)*sin(q(7))*(sin(q(2))*(sin(alpha)*sin(alpha-q(6))+cos(alpha)*cos(q(5))*...
  cos(alpha-q(6)))-cos(q(2))*(sin(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(cos(...
  alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))-cos(q(3))*(sin(q(5))*...
  cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*...
  cos(alpha-q(6)))))) + pull(2)*cos(q(7))*(sin(q(2))*(sin(alpha)*sin(alpha-q(6))+cos(...
  alpha)*cos(q(5))*cos(alpha-q(6)))-cos(q(2))*(sin(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-...
  q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))-...
  cos(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-...
  sin(alpha)*cos(q(5))*cos(alpha-q(6)))))) - pull(3)*(sin(q(2))*(sin(alpha)*cos(alpha-...
  q(6))-cos(alpha)*cos(q(5))*sin(alpha-q(6)))-cos(q(2))*(cos(q(3))*(sin(q(5))*cos(q(4))*sin(...
  alpha-q(6))+sin(q(4))*(cos(alpha)*cos(alpha-q(6))+sin(alpha)*cos(q(5))*sin(alpha-q(6))))-...
  sin(q(3))*(sin(q(4))*sin(q(5))*sin(alpha-q(6))-cos(q(4))*(cos(alpha)*cos(alpha-q(6))+...
  sin(alpha)*cos(q(5))*sin(alpha-q(6))))));
  
Jac(1,7) = pull(1)*(sin(q(2))*(sin(alpha)*cos(q(7))*cos(alpha-q(6))+cos(alpha)*(sin(q(5))*...
  sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))-cos(q(2))*(cos(q(3))*(cos(q(4))*(sin(q(7))*...
  cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(...
  alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))-sin(...
  q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(...
  alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*...
  sin(alpha-q(6))))))) - pull(2)*(sin(q(2))*(sin(alpha)*sin(q(7))*cos(alpha-q(6))-cos(...
  alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))-cos(q(2))*(sin(q(3))*(...
  sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*...
  sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-...
  q(6)))))-cos(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(...
  q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*...
  cos(q(5))*sin(alpha-q(6)))))));
  
Jac(2,1) = pull(2)*(sin(q(1))*(sin(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*...
  sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*...
  sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))+cos(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+...
  sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-...
  sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))-cos(q(1))*(cos(...
  q(2))*(sin(alpha)*cos(q(7))*cos(alpha-q(6))+cos(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*...
  cos(q(7))*sin(alpha-q(6))))+sin(q(2))*(cos(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*...
  cos(q(7))*sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(...
  sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))-sin(q(3))*(sin(q(4))*(sin(q(7))*...
  cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(...
  alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))))) - ...
  La(3)*cos(q(1))*cos(q(2)) - Lb(3)*cos(q(1))*cos(q(2)) - La(2)*(sin(q(1))*cos(q(3))+sin(q(2))*...
  sin(q(3))*cos(q(1))) - La(1)*(sin(q(1))*sin(q(3))-sin(q(2))*cos(q(1))*cos(q(3))) - Lb(2)*(sin(...
  q(1))*cos(q(3)+q(4))+sin(q(2))*cos(q(1))*sin(q(3)+q(4))) - Lb(1)*(sin(q(1))*sin(q(3)+q(4))-sin(q(2))*...
  cos(q(1))*cos(q(3)+q(4))) - Lc(2)*(cos(alpha)*sin(q(1))*cos(q(3)+q(4))+cos(q(1))*(sin(alpha)*...
  cos(q(2))+cos(alpha)*sin(q(2))*sin(q(3)+q(4)))) - Lc(3)*(sin(q(1))*(sin(q(3))*(sin(q(5))*...
  cos(q(4))+sin(alpha)*sin(q(4))*cos(q(5)))+cos(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(...
  q(4))*cos(q(5))))+cos(q(1))*(cos(alpha)*cos(q(2))*cos(q(5))-sin(q(2))*(cos(q(3))*(sin(q(5))*...
  cos(q(4))+sin(alpha)*sin(q(4))*cos(q(5)))-sin(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(...
  q(4))*cos(q(5)))))) - Lc(1)*(sin(q(1))*(cos(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*...
  cos(q(4)))+sin(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))-cos(q(1))*(cos(...
  alpha)*sin(q(5))*cos(q(2))-sin(q(2))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*...
  cos(q(4)))-cos(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5)))))) - pull(3)*(...
  sin(q(1))*(cos(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(cos(alpha)*sin(...
  alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))+sin(q(3))*(sin(q(5))*cos(q(4))*cos(...
  alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6)))))+...
  cos(q(1))*(cos(q(2))*(sin(alpha)*sin(alpha-q(6))+cos(alpha)*cos(q(5))*cos(alpha-q(6)))+...
  sin(q(2))*(sin(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(cos(alpha)*sin(...
  alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))-cos(q(3))*(sin(q(5))*cos(q(4))*cos(...
  alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))))) - ...
  pull(1)*(sin(q(1))*(cos(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-...
  q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+...
  sin(q(7))*cos(q(5))*sin(alpha-q(6)))))+sin(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*...
  sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(...
  sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))+cos(q(1))*(cos(q(2))*(sin(...
  alpha)*sin(q(7))*cos(alpha-q(6))-cos(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*...
  sin(alpha-q(6))))+sin(q(2))*(sin(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*...
  sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*...
  cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))-cos(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-...
  sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+...
  sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))));
  
Jac(2,2) = -sin(q(1))*(La(2)*sin(q(3))*cos(q(2))+Lb(2)*cos(q(2))*sin(q(3)+q(4))+Lc(1)*(cos(alpha)*...
  sin(q(2))*sin(q(5))+cos(q(2))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-...
  cos(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5)))))-La(3)*sin(q(2))-Lb(3)*sin(...
  q(2))-La(1)*cos(q(2))*cos(q(3))-Lb(1)*cos(q(2))*cos(q(3)+q(4))-Lc(2)*(sin(alpha)*sin(q(2))-cos(...
  alpha)*cos(q(2))*sin(q(3)+q(4)))-Lc(3)*(cos(alpha)*sin(q(2))*cos(q(5))+cos(q(2))*(cos(q(3))*(...
  sin(q(5))*cos(q(4))+sin(alpha)*sin(q(4))*cos(q(5)))-sin(q(3))*(sin(q(4))*sin(q(5))-sin(...
  alpha)*cos(q(4))*cos(q(5)))))-pull(3)*(sin(q(2))*(sin(alpha)*sin(alpha-q(6))+cos(...
  alpha)*cos(q(5))*cos(alpha-q(6)))-cos(q(2))*(sin(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-...
  q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))-...
  cos(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-...
  sin(alpha)*cos(q(5))*cos(alpha-q(6))))))-pull(1)*(sin(q(2))*(sin(alpha)*sin(q(7))*cos(...
  alpha-q(6))-cos(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))-cos(...
  q(2))*(sin(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))+cos(...
  q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*...
  cos(q(5))*sin(alpha-q(6)))))-cos(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*...
  sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*...
  cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))))-pull(2)*(sin(q(2))*(sin(alpha)*cos(...
  q(7))*cos(alpha-q(6))+cos(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))-...
  cos(q(2))*(cos(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))+...
  sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(...
  q(5))*cos(q(7))*sin(alpha-q(6)))))-sin(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(...
  q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(...
  sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))));
  
Jac(2,3) = La(1)*(cos(q(1))*cos(q(3))-sin(q(1))*sin(q(2))*sin(q(3))) + Lb(1)*(cos(q(1))*cos(q(3)+...
  q(4))-sin(q(1))*sin(q(2))*sin(q(3)+q(4))) + Lc(3)*(cos(q(1))*(cos(q(3))*(sin(q(5))*cos(q(4))+...
  sin(alpha)*sin(q(4))*cos(q(5)))-sin(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(...
  q(5))))-sin(q(1))*sin(q(2))*(sin(q(3))*(sin(q(5))*cos(q(4))+sin(alpha)*sin(q(4))*cos(q(5)))+...
  cos(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(q(5))))) - La(2)*(sin(q(3))*cos(...
  q(1))+sin(q(1))*sin(q(2))*cos(q(3))) - Lb(2)*(cos(q(1))*sin(q(3)+q(4))+sin(q(1))*sin(q(2))*cos(...
  q(3)+q(4))) - Lc(2)*cos(alpha)*(cos(q(1))*sin(q(3)+q(4))+sin(q(1))*sin(q(2))*cos(q(3)+q(4))) - ...
  Lc(1)*(cos(q(1))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-cos(q(3))*(...
  cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))+sin(q(1))*sin(q(2))*(cos(q(3))*(sin(...
  q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))+sin(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*...
  sin(q(4))*sin(q(5))))) - pull(3)*(cos(q(1))*(sin(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-q(6))+...
  cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))-cos(q(3))*(...
  sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*...
  cos(q(5))*cos(alpha-q(6)))))+sin(q(1))*sin(q(2))*(cos(q(3))*(sin(q(4))*sin(q(5))*cos(...
  alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))+...
  sin(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-...
  sin(alpha)*cos(q(5))*cos(alpha-q(6)))))) - pull(1)*(cos(q(1))*(sin(q(3))*(sin(q(4))*(...
  cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*...
  cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))-...
  cos(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(...
  cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*...
  sin(alpha-q(6))))))+sin(q(1))*sin(q(2))*(cos(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*...
  sin(q(7))*sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(...
  sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))+sin(q(3))*(cos(q(4))*(cos(q(5))*...
  cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(...
  alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))) -... 
  pull(2)*(cos(q(1))*(cos(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-...
  q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-...
  cos(q(5))*cos(q(7))*sin(alpha-q(6)))))-sin(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*...
  cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(...
  sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))-sin(q(1))*sin(q(2))*(sin(q(3))*(...
  cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*...
  cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-...
  q(6)))))+cos(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(...
  q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*...
  cos(q(7))*sin(alpha-q(6)))))));
  
Jac(2,4) = Lb(1)*(cos(q(1))*cos(q(3)+q(4))-sin(q(1))*sin(q(2))*sin(q(3)+q(4))) + Lc(3)*(cos(q(1))*(...
  cos(q(3))*(sin(q(5))*cos(q(4))+sin(alpha)*sin(q(4))*cos(q(5)))-sin(q(3))*(sin(q(4))*sin(...
  q(5))-sin(alpha)*cos(q(4))*cos(q(5))))-sin(q(1))*sin(q(2))*(sin(q(3))*(sin(q(5))*cos(q(4))+...
  sin(alpha)*sin(q(4))*cos(q(5)))+cos(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(...
  q(5))))) - Lb(2)*(cos(q(1))*sin(q(3)+q(4))+sin(q(1))*sin(q(2))*cos(q(3)+q(4))) - Lc(2)*cos(...
  alpha)*(cos(q(1))*sin(q(3)+q(4))+sin(q(1))*sin(q(2))*cos(q(3)+q(4))) - Lc(1)*(cos(q(1))*(sin(...
  q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-cos(q(3))*(cos(q(4))*cos(q(5))-...
  sin(alpha)*sin(q(4))*sin(q(5))))+sin(q(1))*sin(q(2))*(cos(q(3))*(sin(q(4))*cos(q(5))+sin(...
  alpha)*sin(q(5))*cos(q(4)))+sin(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))) - ...
  pull(3)*(cos(q(1))*(sin(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(cos(alpha)*...
  sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))-cos(q(3))*(sin(q(5))*cos(q(4))*...
  cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(...
  alpha-q(6)))))+sin(q(1))*sin(q(2))*(cos(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(...
  cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))+sin(q(3))*(sin(q(5))*...
  cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*...
  cos(alpha-q(6)))))) - pull(1)*(cos(q(1))*(sin(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(...
  q(5))*sin(q(7))*sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(...
  alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))-cos(q(3))*(cos(q(4))*(...
  cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*...
  cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))+...
  sin(q(1))*sin(q(2))*(cos(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(...
  alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*...
  cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))+sin(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-...
  sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+...
  sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))) - pull(2)*(cos(...
  q(1))*(cos(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(...
  q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*...
  cos(q(7))*sin(alpha-q(6)))))-sin(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*...
  sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*...
  sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))-sin(q(1))*sin(q(2))*(sin(q(3))*(cos(q(4))*(...
  sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*...
  cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))+...
  cos(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(...
  cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*...
  sin(alpha-q(6)))))));
  
Jac(2,5) = Lc(3)*(cos(q(1))*(cos(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))+...
  sin(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))+sin(q(1))*(cos(alpha)*...
  sin(q(5))*cos(q(2))-sin(q(2))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-...
  cos(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5)))))) + pull(3)*cos(alpha-...
  q(6))*(cos(q(1))*(cos(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))+sin(q(3))*(...
  cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))+sin(q(1))*(cos(alpha)*sin(q(5))*...
  cos(q(2))-sin(q(2))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-cos(...
  q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5)))))) + pull(2)*(cos(q(1))*(sin(...
  q(3))*(cos(q(4))*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(alpha)*sin(...
  q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6))))+cos(q(3))*(sin(q(4))*(sin(...
  q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))-sin(alpha)*cos(q(4))*(sin(q(7))*cos(...
  q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))))-sin(q(1))*(cos(alpha)*cos(q(2))*(sin(q(7))*...
  cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))-sin(q(2))*(cos(q(3))*(cos(q(4))*(sin(q(5))*...
  sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(alpha)*sin(q(4))*(sin(q(7))*cos(q(5))+...
  sin(q(5))*cos(q(7))*sin(alpha-q(6))))-sin(q(3))*(sin(q(4))*(sin(q(5))*sin(q(7))-cos(q(5))*...
  cos(q(7))*sin(alpha-q(6)))-sin(alpha)*cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*...
  sin(alpha-q(6))))))) - Lc(1)*(cos(q(1))*(sin(q(3))*(sin(q(5))*cos(q(4))+sin(alpha)*sin(...
  q(4))*cos(q(5)))+cos(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(q(5))))-sin(q(1))*(...
  cos(alpha)*cos(q(2))*cos(q(5))-sin(q(2))*(cos(q(3))*(sin(q(5))*cos(q(4))+sin(alpha)*sin(...
  q(4))*cos(q(5)))-sin(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(q(5)))))) - ...
  pull(1)*(cos(q(1))*(sin(q(3))*(cos(q(4))*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-...
  q(6)))+sin(alpha)*sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6))))+...
  cos(q(3))*(sin(q(4))*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))-sin(alpha)*...
  cos(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))))-sin(q(1))*(cos(...
  alpha)*cos(q(2))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(2))*(cos(...
  q(3))*(cos(q(4))*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))+sin(alpha)*sin(...
  q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6))))-sin(q(3))*(sin(q(4))*(sin(...
  q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))-sin(alpha)*cos(q(4))*(cos(q(5))*cos(...
  q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))))));
  
Jac(2,6) = pull(3)*(cos(q(1))*(sin(q(3))*(sin(q(5))*cos(q(4))*sin(alpha-q(6))+sin(q(4))*(cos(...
  alpha)*cos(alpha-q(6))+sin(alpha)*cos(q(5))*sin(alpha-q(6))))+cos(q(3))*(sin(q(4))*...
  sin(q(5))*sin(alpha-q(6))-cos(q(4))*(cos(alpha)*cos(alpha-q(6))+sin(alpha)*cos(q(5))*...
  sin(alpha-q(6)))))+sin(q(1))*(cos(q(2))*(sin(alpha)*cos(alpha-q(6))-cos(alpha)*cos(...
  q(5))*sin(alpha-q(6)))+sin(q(2))*(cos(q(3))*(sin(q(5))*cos(q(4))*sin(alpha-q(6))+sin(q(4))*(...
  cos(alpha)*cos(alpha-q(6))+sin(alpha)*cos(q(5))*sin(alpha-q(6))))-sin(q(3))*(sin(q(4))*...
  sin(q(5))*sin(alpha-q(6))-cos(q(4))*(cos(alpha)*cos(alpha-q(6))+sin(alpha)*cos(q(5))*...
  sin(alpha-q(6))))))) + pull(1)*sin(q(7))*(cos(q(1))*(cos(q(3))*(sin(q(4))*sin(q(5))*cos(...
  alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))+...
  sin(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-...
  sin(alpha)*cos(q(5))*cos(alpha-q(6)))))-sin(q(1))*(cos(q(2))*(sin(alpha)*sin(alpha-...
  q(6))+cos(alpha)*cos(q(5))*cos(alpha-q(6)))+sin(q(2))*(sin(q(3))*(sin(q(4))*sin(q(5))*cos(...
  alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))-...
  cos(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-...
  sin(alpha)*cos(q(5))*cos(alpha-q(6))))))) + pull(2)*cos(q(7))*(cos(q(1))*(cos(q(3))*(...
  sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*...
  cos(q(5))*cos(alpha-q(6))))+sin(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(...
  alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6)))))-sin(q(1))*(cos(q(2))*(...
  sin(alpha)*sin(alpha-q(6))+cos(alpha)*cos(q(5))*cos(alpha-q(6)))+sin(q(2))*(sin(q(3))*(...
  sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*...
  cos(q(5))*cos(alpha-q(6))))-cos(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(...
  alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6)))))));
  
Jac(2,7) = -pull(2)*(cos(q(1))*(cos(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*...
  sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*...
  cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))+sin(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-...
  sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+...
  sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))-sin(q(1))*(cos(...
  q(2))*(sin(alpha)*sin(q(7))*cos(alpha-q(6))-cos(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*...
  cos(q(5))*sin(alpha-q(6))))+sin(q(2))*(sin(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*...
  sin(q(7))*sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(...
  sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))-cos(q(3))*(cos(q(4))*(cos(q(5))*...
  cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(...
  alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))))) - ...
  pull(1)*(cos(q(1))*(sin(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-...
  q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-...
  cos(q(5))*cos(q(7))*sin(alpha-q(6)))))+cos(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*...
  cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(...
  sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))+sin(q(1))*(cos(q(2))*(sin(...
  alpha)*cos(q(7))*cos(alpha-q(6))+cos(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*...
  sin(alpha-q(6))))+sin(q(2))*(cos(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*...
  sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*...
  sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))-sin(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+...
  sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-...
  sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))));
  
Jac(3,1) = La(1)*(sin(q(3))*cos(q(1))+sin(q(1))*sin(q(2))*cos(q(3))) + La(2)*(cos(q(1))*cos(q(3))-...
  sin(q(1))*sin(q(2))*sin(q(3))) + Lb(1)*(cos(q(1))*sin(q(3)+q(4))+sin(q(1))*sin(q(2))*cos(q(3)+...
  q(4))) + Lb(2)*(cos(q(1))*cos(q(3)+q(4))-sin(q(1))*sin(q(2))*sin(q(3)+q(4))) + Lc(2)*(cos(alpha)*...
  cos(q(1))*cos(q(3)+q(4))-sin(q(1))*(sin(alpha)*cos(q(2))+cos(alpha)*sin(q(2))*sin(q(3)+q(4)))) + ...
  Lc(1)*(cos(q(1))*(cos(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))+sin(q(3))*(...
  cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))+sin(q(1))*(cos(alpha)*sin(q(5))*...
  cos(q(2))-sin(q(2))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-cos(...
  q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5)))))) + Lc(3)*(cos(q(1))*(sin(q(3))*(...
  sin(q(5))*cos(q(4))+sin(alpha)*sin(q(4))*cos(q(5)))+cos(q(3))*(sin(q(4))*sin(q(5))-sin(...
  alpha)*cos(q(4))*cos(q(5))))-sin(q(1))*(cos(alpha)*cos(q(2))*cos(q(5))-sin(q(2))*(cos(...
  q(3))*(sin(q(5))*cos(q(4))+sin(alpha)*sin(q(4))*cos(q(5)))-sin(q(3))*(sin(q(4))*sin(q(5))-...
  sin(alpha)*cos(q(4))*cos(q(5)))))) + pull(3)*(cos(q(1))*(cos(q(3))*(sin(q(4))*sin(q(5))*...
  cos(alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(...
  alpha-q(6))))+sin(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(...
  alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6)))))-sin(q(1))*(cos(q(2))*(sin(alpha)*...
  sin(alpha-q(6))+cos(alpha)*cos(q(5))*cos(alpha-q(6)))+sin(q(2))*(sin(q(3))*(sin(q(4))*...
  sin(q(5))*cos(alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*...
  cos(alpha-q(6))))-cos(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*...
  sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))))) + pull(1)*(cos(q(1))*(cos(...
  q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))+cos(q(4))*(cos(...
  alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*...
  sin(alpha-q(6)))))+sin(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(...
  alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*...
  cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))-sin(q(1))*(cos(q(2))*(sin(alpha)*sin(...
  q(7))*cos(alpha-q(6))-cos(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))+...
  sin(q(2))*(sin(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))+...
  cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(...
  q(7))*cos(q(5))*sin(alpha-q(6)))))-cos(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(...
  q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(...
  sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))))) - La(3)*sin(q(1))*cos(q(2)) - ...
  Lb(3)*sin(q(1))*cos(q(2)) - pull(2)*(cos(q(1))*(sin(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(...
  q(5))*cos(q(7))*sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(...
  alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))+cos(q(3))*(sin(q(4))*(...
  sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*...
  cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))+...
  sin(q(1))*(cos(q(2))*(sin(alpha)*cos(q(7))*cos(alpha-q(6))+cos(alpha)*(sin(q(5))*sin(...
  q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))+sin(q(2))*(cos(q(3))*(cos(q(4))*(sin(q(7))*cos(...
  q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-...
  sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))-sin(q(3))*(sin(...
  q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(...
  q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))));
  
Jac(3,2) = cos(q(1))*(La(2)*sin(q(3))*cos(q(2))+Lb(2)*cos(q(2))*sin(q(3)+q(4))+Lc(1)*(cos(alpha)*...
  sin(q(2))*sin(q(5))+cos(q(2))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-...
  cos(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5)))))-La(3)*sin(q(2))-Lb(3)*sin(...
  q(2))-La(1)*cos(q(2))*cos(q(3))-Lb(1)*cos(q(2))*cos(q(3)+q(4))-Lc(2)*(sin(alpha)*sin(q(2))-cos(...
  alpha)*cos(q(2))*sin(q(3)+q(4)))-Lc(3)*(cos(alpha)*sin(q(2))*cos(q(5))+cos(q(2))*(cos(q(3))*(...
  sin(q(5))*cos(q(4))+sin(alpha)*sin(q(4))*cos(q(5)))-sin(q(3))*(sin(q(4))*sin(q(5))-sin(...
  alpha)*cos(q(4))*cos(q(5)))))-pull(3)*(sin(q(2))*(sin(alpha)*sin(alpha-q(6))+cos(...
  alpha)*cos(q(5))*cos(alpha-q(6)))-cos(q(2))*(sin(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-...
  q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))-...
  cos(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-...
  sin(alpha)*cos(q(5))*cos(alpha-q(6))))))-pull(1)*(sin(q(2))*(sin(alpha)*sin(q(7))*cos(...
  alpha-q(6))-cos(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))-cos(...
  q(2))*(sin(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))+cos(...
  q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*...
  cos(q(5))*sin(alpha-q(6)))))-cos(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*...
  sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*...
  cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))))-pull(2)*(sin(q(2))*(sin(alpha)*cos(...
  q(7))*cos(alpha-q(6))+cos(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))-...
  cos(q(2))*(cos(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))+...
  sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(...
  q(5))*cos(q(7))*sin(alpha-q(6)))))-sin(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(...
  q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(...
  sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))));
  
Jac(3,3) = La(1)*(sin(q(1))*cos(q(3))+sin(q(2))*sin(q(3))*cos(q(1))) + Lb(1)*(sin(q(1))*cos(q(3)+...
  q(4))+sin(q(2))*cos(q(1))*sin(q(3)+q(4))) + Lc(3)*(sin(q(1))*(cos(q(3))*(sin(q(5))*cos(q(4))+...
  sin(alpha)*sin(q(4))*cos(q(5)))-sin(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(...
  q(5))))+sin(q(2))*cos(q(1))*(sin(q(3))*(sin(q(5))*cos(q(4))+sin(alpha)*sin(q(4))*cos(q(5)))+...
  cos(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(q(5))))) - La(2)*(sin(q(1))*sin(...
  q(3))-sin(q(2))*cos(q(1))*cos(q(3))) - Lb(2)*(sin(q(1))*sin(q(3)+q(4))-sin(q(2))*cos(q(1))*cos(...
  q(3)+q(4))) - Lc(2)*cos(alpha)*(sin(q(1))*sin(q(3)+q(4))-sin(q(2))*cos(q(1))*cos(q(3)+q(4))) - ...
  Lc(1)*(sin(q(1))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-cos(q(3))*(...
  cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))-sin(q(2))*cos(q(1))*(cos(q(3))*(sin(...
  q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))+sin(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*...
  sin(q(4))*sin(q(5))))) - pull(3)*(sin(q(1))*(sin(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-q(6))+...
  cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))-cos(q(3))*(...
  sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*...
  cos(q(5))*cos(alpha-q(6)))))-sin(q(2))*cos(q(1))*(cos(q(3))*(sin(q(4))*sin(q(5))*cos(...
  alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))+...
  sin(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-...
  sin(alpha)*cos(q(5))*cos(alpha-q(6)))))) - pull(1)*(sin(q(1))*(sin(q(3))*(sin(q(4))*(...
  cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*...
  cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))-...
  cos(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(...
  cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*...
  sin(alpha-q(6))))))-sin(q(2))*cos(q(1))*(cos(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*...
  sin(q(7))*sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(...
  sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))+sin(q(3))*(cos(q(4))*(cos(q(5))*...
  cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(...
  alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))) -... 
  pull(2)*(sin(q(1))*(cos(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-...
  q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-...
  cos(q(5))*cos(q(7))*sin(alpha-q(6)))))-sin(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*...
  cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(...
  sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))+sin(q(2))*cos(q(1))*(sin(q(3))*(...
  cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*...
  cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-...
  q(6)))))+cos(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(...
  q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*...
  cos(q(7))*sin(alpha-q(6)))))));
  
Jac(3,4) = Lb(1)*(sin(q(1))*cos(q(3)+q(4))+sin(q(2))*cos(q(1))*sin(q(3)+q(4))) + Lc(3)*(sin(q(1))*(...
  cos(q(3))*(sin(q(5))*cos(q(4))+sin(alpha)*sin(q(4))*cos(q(5)))-sin(q(3))*(sin(q(4))*sin(...
  q(5))-sin(alpha)*cos(q(4))*cos(q(5))))+sin(q(2))*cos(q(1))*(sin(q(3))*(sin(q(5))*cos(q(4))+...
  sin(alpha)*sin(q(4))*cos(q(5)))+cos(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(...
  q(5))))) - Lb(2)*(sin(q(1))*sin(q(3)+q(4))-sin(q(2))*cos(q(1))*cos(q(3)+q(4))) - Lc(2)*cos(...
  alpha)*(sin(q(1))*sin(q(3)+q(4))-sin(q(2))*cos(q(1))*cos(q(3)+q(4))) - Lc(1)*(sin(q(1))*(sin(...
  q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-cos(q(3))*(cos(q(4))*cos(q(5))-...
  sin(alpha)*sin(q(4))*sin(q(5))))-sin(q(2))*cos(q(1))*(cos(q(3))*(sin(q(4))*cos(q(5))+sin(...
  alpha)*sin(q(5))*cos(q(4)))+sin(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))) - ...
  pull(3)*(sin(q(1))*(sin(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(cos(alpha)*...
  sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))-cos(q(3))*(sin(q(5))*cos(q(4))*...
  cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(...
  alpha-q(6)))))-sin(q(2))*cos(q(1))*(cos(q(3))*(sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(...
  cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))+sin(q(3))*(sin(q(5))*...
  cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*...
  cos(alpha-q(6)))))) - pull(1)*(sin(q(1))*(sin(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(...
  q(5))*sin(q(7))*sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(...
  alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))-cos(q(3))*(cos(q(4))*(...
  cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*...
  cos(alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))-...
  sin(q(2))*cos(q(1))*(cos(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(...
  alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*...
  cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))+sin(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-...
  sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+...
  sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))) - pull(2)*(sin(...
  q(1))*(cos(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(...
  q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*...
  cos(q(7))*sin(alpha-q(6)))))-sin(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*...
  sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*...
  sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))+sin(q(2))*cos(q(1))*(sin(q(3))*(cos(q(4))*(...
  sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*...
  cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))+...
  cos(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(...
  cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*...
  sin(alpha-q(6)))))));
  
Jac(3,5) = Lc(3)*(sin(q(1))*(cos(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))+...
  sin(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))-cos(q(1))*(cos(alpha)*...
  sin(q(5))*cos(q(2))-sin(q(2))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-...
  cos(q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5)))))) + pull(3)*cos(alpha-...
  q(6))*(sin(q(1))*(cos(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))+sin(q(3))*(...
  cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5))))-cos(q(1))*(cos(alpha)*sin(q(5))*...
  cos(q(2))-sin(q(2))*(sin(q(3))*(sin(q(4))*cos(q(5))+sin(alpha)*sin(q(5))*cos(q(4)))-cos(...
  q(3))*(cos(q(4))*cos(q(5))-sin(alpha)*sin(q(4))*sin(q(5)))))) + pull(2)*(sin(q(1))*(sin(...
  q(3))*(cos(q(4))*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(alpha)*sin(...
  q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6))))+cos(q(3))*(sin(q(4))*(sin(...
  q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))-sin(alpha)*cos(q(4))*(sin(q(7))*cos(...
  q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))))+cos(q(1))*(cos(alpha)*cos(q(2))*(sin(q(7))*...
  cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-q(6)))-sin(q(2))*(cos(q(3))*(cos(q(4))*(sin(q(5))*...
  sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))+sin(alpha)*sin(q(4))*(sin(q(7))*cos(q(5))+...
  sin(q(5))*cos(q(7))*sin(alpha-q(6))))-sin(q(3))*(sin(q(4))*(sin(q(5))*sin(q(7))-cos(q(5))*...
  cos(q(7))*sin(alpha-q(6)))-sin(alpha)*cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*...
  sin(alpha-q(6))))))) - Lc(1)*(sin(q(1))*(sin(q(3))*(sin(q(5))*cos(q(4))+sin(alpha)*sin(...
  q(4))*cos(q(5)))+cos(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(q(5))))+cos(q(1))*(...
  cos(alpha)*cos(q(2))*cos(q(5))-sin(q(2))*(cos(q(3))*(sin(q(5))*cos(q(4))+sin(alpha)*sin(...
  q(4))*cos(q(5)))-sin(q(3))*(sin(q(4))*sin(q(5))-sin(alpha)*cos(q(4))*cos(q(5)))))) - ...
  pull(1)*(sin(q(1))*(sin(q(3))*(cos(q(4))*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-...
  q(6)))+sin(alpha)*sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6))))+...
  cos(q(3))*(sin(q(4))*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))-sin(alpha)*...
  cos(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))))+cos(q(1))*(cos(...
  alpha)*cos(q(2))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(2))*(cos(...
  q(3))*(cos(q(4))*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))+sin(alpha)*sin(...
  q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6))))-sin(q(3))*(sin(q(4))*(sin(...
  q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))-sin(alpha)*cos(q(4))*(cos(q(5))*cos(...
  q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))))));
  
Jac(3,6) = pull(3)*(sin(q(1))*(sin(q(3))*(sin(q(5))*cos(q(4))*sin(alpha-q(6))+sin(q(4))*(cos(...
  alpha)*cos(alpha-q(6))+sin(alpha)*cos(q(5))*sin(alpha-q(6))))+cos(q(3))*(sin(q(4))*...
  sin(q(5))*sin(alpha-q(6))-cos(q(4))*(cos(alpha)*cos(alpha-q(6))+sin(alpha)*cos(q(5))*...
  sin(alpha-q(6)))))-cos(q(1))*(cos(q(2))*(sin(alpha)*cos(alpha-q(6))-cos(alpha)*cos(...
  q(5))*sin(alpha-q(6)))+sin(q(2))*(cos(q(3))*(sin(q(5))*cos(q(4))*sin(alpha-q(6))+sin(q(4))*(...
  cos(alpha)*cos(alpha-q(6))+sin(alpha)*cos(q(5))*sin(alpha-q(6))))-sin(q(3))*(sin(q(4))*...
  sin(q(5))*sin(alpha-q(6))-cos(q(4))*(cos(alpha)*cos(alpha-q(6))+sin(alpha)*cos(q(5))*...
  sin(alpha-q(6))))))) + pull(1)*sin(q(7))*(sin(q(1))*(cos(q(3))*(sin(q(4))*sin(q(5))*cos(...
  alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))+...
  sin(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-...
  sin(alpha)*cos(q(5))*cos(alpha-q(6)))))+cos(q(1))*(cos(q(2))*(sin(alpha)*sin(alpha-...
  q(6))+cos(alpha)*cos(q(5))*cos(alpha-q(6)))+sin(q(2))*(sin(q(3))*(sin(q(4))*sin(q(5))*cos(...
  alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6))))-...
  cos(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(alpha)*sin(alpha-q(6))-...
  sin(alpha)*cos(q(5))*cos(alpha-q(6))))))) + pull(2)*cos(q(7))*(sin(q(1))*(cos(q(3))*(...
  sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*...
  cos(q(5))*cos(alpha-q(6))))+sin(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(...
  alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6)))))+cos(q(1))*(cos(q(2))*(...
  sin(alpha)*sin(alpha-q(6))+cos(alpha)*cos(q(5))*cos(alpha-q(6)))+sin(q(2))*(sin(q(3))*(...
  sin(q(4))*sin(q(5))*cos(alpha-q(6))+cos(q(4))*(cos(alpha)*sin(alpha-q(6))-sin(alpha)*...
  cos(q(5))*cos(alpha-q(6))))-cos(q(3))*(sin(q(5))*cos(q(4))*cos(alpha-q(6))-sin(q(4))*(cos(...
  alpha)*sin(alpha-q(6))-sin(alpha)*cos(q(5))*cos(alpha-q(6)))))));
  
Jac(3,7) = -pull(2)*(sin(q(1))*(cos(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*sin(q(7))*...
  sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(sin(q(5))*...
  cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))+sin(q(3))*(cos(q(4))*(cos(q(5))*cos(q(7))-...
  sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+...
  sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6))))))+cos(q(1))*(cos(...
  q(2))*(sin(alpha)*sin(q(7))*cos(alpha-q(6))-cos(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*...
  cos(q(5))*sin(alpha-q(6))))+sin(q(2))*(sin(q(3))*(sin(q(4))*(cos(q(5))*cos(q(7))-sin(q(5))*...
  sin(q(7))*sin(alpha-q(6)))+cos(q(4))*(cos(alpha)*sin(q(7))*cos(alpha-q(6))+sin(alpha)*(...
  sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))-cos(q(3))*(cos(q(4))*(cos(q(5))*...
  cos(q(7))-sin(q(5))*sin(q(7))*sin(alpha-q(6)))-sin(q(4))*(cos(alpha)*sin(q(7))*cos(...
  alpha-q(6))+sin(alpha)*(sin(q(5))*cos(q(7))+sin(q(7))*cos(q(5))*sin(alpha-q(6)))))))) - ...
  pull(1)*(sin(q(1))*(sin(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*sin(alpha-...
  q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*sin(q(7))-...
  cos(q(5))*cos(q(7))*sin(alpha-q(6)))))+cos(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*...
  cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(...
  sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))-cos(q(1))*(cos(q(2))*(sin(...
  alpha)*cos(q(7))*cos(alpha-q(6))+cos(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*...
  sin(alpha-q(6))))+sin(q(2))*(cos(q(3))*(cos(q(4))*(sin(q(7))*cos(q(5))+sin(q(5))*cos(q(7))*...
  sin(alpha-q(6)))+sin(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-sin(alpha)*(sin(q(5))*...
  sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6)))))-sin(q(3))*(sin(q(4))*(sin(q(7))*cos(q(5))+...
  sin(q(5))*cos(q(7))*sin(alpha-q(6)))-cos(q(4))*(cos(alpha)*cos(q(7))*cos(alpha-q(6))-...
  sin(alpha)*(sin(q(5))*sin(q(7))-cos(q(5))*cos(q(7))*sin(alpha-q(6))))))));
