days={...
    '09-02-2011', ...
    '09-06-2011', ...
    '09-07-2011', ...
    '09-08-2011', ...
    '09-09-2011', ...
    '03-19-2012', ...
    '03-21-2012', ...
    '03-26-2012', ...
    '03-28-2012', ...
    '03-30-2012', ...
    };

peakIndAll_x=[]; peakIndAll_y=[]; peakValAll_x=[]; peakValAll_y=[];
BDFlist_all=[];
for n=1:length(days)
    % take a day, find the kinStruct, and identifies all the
    % files of the given control type that were included.
    BDFlist=findBDF_withControl('Chewie',days{n},'LFP');
    BDFlist_all=[BDFlist_all; BDFlist'];
    for k=1:length(BDFlist)
        run_makefmatc_causal(BDFlist{k},500)
        peakIndAll_x=[peakIndAll_x; evalin('base','peakInd_x')];
        peakIndAll_y=[peakIndAll_y; evalin('base','peakInd_y')];
        peakValAll_x=[peakValAll_x; evalin('base','peakVal_x')];
        peakValAll_y=[peakValAll_y; evalin('base','peakVal_y')];
    end
end
