% given a PB matrix, generate an array of bands decoded by other bands.

vaf_decodeLMP_sameElectrode=bandsFromBands(PB,1,NaN,0,1);
vaf_decode0_4_sameElectrode=bandsFromBands(PB,2,NaN,0,1);
vaf_decode7_20_sameElectrode=bandsFromBands(PB,3,NaN,0,1);
vaf_decode70_110_sameElectrode=bandsFromBands(PB,4,NaN,0,1);
vaf_decode130_200_sameElectrode=bandsFromBands(PB,5,NaN,0,1);
vaf_decode200_300_sameElectrode=bandsFromBands(PB,6,NaN,0,1);

% build an array out of the median values
medVals=[nanmedian(reshape(cellfun(@nanmedian,{vaf_decodeLMP_sameElectrode.vaf}), ...
    size(vaf_decodeLMP_sameElectrode)),2), ...
    nanmedian(reshape(cellfun(@nanmedian,{vaf_decode0_4_sameElectrode.vaf}), ...
    size(vaf_decode0_4_sameElectrode)),2), ...
    nanmedian(reshape(cellfun(@nanmedian,{vaf_decode7_20_sameElectrode.vaf}), ...
    size(vaf_decode7_20_sameElectrode)),2), ...
    nanmedian(reshape(cellfun(@nanmedian,{vaf_decode70_110_sameElectrode.vaf}), ...
    size(vaf_decode70_110_sameElectrode)),2), ...
    nanmedian(reshape(cellfun(@nanmedian,{vaf_decode130_200_sameElectrode.vaf}), ...
    size(vaf_decode130_200_sameElectrode)),2), ...
    [nanmedian(reshape(cellfun(@nanmedian,{vaf_decode200_300_sameElectrode.vaf}), ...
    size(vaf_decode200_300_sameElectrode)),2); NaN]];

% the main diagonal will be all NaNs (check), because the test band is 
% skipped over by the bandsFromBands code.  supply these values by force 
% testing on the same band.

vaf_decodeLMP_sameElectrode_test=bandsFromBands(PB,1,NaN,1,1);
vaf_decode0_4_sameElectrode_test=bandsFromBands(PB,2,NaN,1,1);
vaf_decode7_20_sameElectrode_test=bandsFromBands(PB,3,NaN,1,1);
vaf_decode70_110_sameElectrode_test=bandsFromBands(PB,4,NaN,1,1);
vaf_decode130_200_sameElectrode_test=bandsFromBands(PB,5,NaN,1,1);
vaf_decode200_300_sameElectrode_test=bandsFromBands(PB,6,NaN,1,1);

mainDiag=[nanmedian(cellfun(@nanmedian,{vaf_decodeLMP_sameElectrode_test.vaf})), ...
    nanmedian(cellfun(@nanmedian,{vaf_decode0_4_sameElectrode_test.vaf})), ...
    nanmedian(cellfun(@nanmedian,{vaf_decode7_20_sameElectrode_test.vaf})), ...
    nanmedian(cellfun(@nanmedian,{vaf_decode70_110_sameElectrode_test.vaf})), ...
    nanmedian(cellfun(@nanmedian,{vaf_decode130_200_sameElectrode_test.vaf})), ...
    nanmedian(cellfun(@nanmedian,{vaf_decode200_300_sameElectrode_test.vaf}))];

medVals(isnan(medVals))=0;
disp1=medVals+diag(mainDiag); openvar('disp1')


%% display the MI 
MImat=[median(reshape(cellfun(@nanmedian,{vaf_decodeLMP_sameElectrode.MI}),size(vaf_decodeLMP_sameElectrode)),2), ...
    median(reshape(cellfun(@nanmedian,{vaf_decode0_4_sameElectrode.MI}),size(vaf_decode0_4_sameElectrode)),2), ...
    median(reshape(cellfun(@nanmedian,{vaf_decode7_20_sameElectrode.MI}),size(vaf_decode7_20_sameElectrode)),2), ...
    median(reshape(cellfun(@nanmedian,{vaf_decode70_110_sameElectrode.MI}),size(vaf_decode70_110_sameElectrode)),2), ...
    median(reshape(cellfun(@nanmedian,{vaf_decode130_200_sameElectrode.MI}),size(vaf_decode130_200_sameElectrode)),2), ...
    [median(reshape(cellfun(@nanmedian,{vaf_decode200_300_sameElectrode.MI}),size(vaf_decode200_300_sameElectrode)),2); NaN]];


mainDiagMI=[nanmedian(cellfun(@nanmedian,{vaf_decodeLMP_sameElectrode_test.MI})), ...
    nanmedian(cellfun(@nanmedian,{vaf_decode0_4_sameElectrode_test.MI})), ...
    nanmedian(cellfun(@nanmedian,{vaf_decode7_20_sameElectrode_test.MI})), ...
    nanmedian(cellfun(@nanmedian,{vaf_decode70_110_sameElectrode_test.MI})), ...
    nanmedian(cellfun(@nanmedian,{vaf_decode130_200_sameElectrode_test.MI})), ...
    nanmedian(cellfun(@nanmedian,{vaf_decode200_300_sameElectrode_test.MI}))];

MImat(isnan(MImat))=0;
disp2=MImat+diag(mainDiagMI); openvar('disp2')

