function update_arm_figure(hFig,arm_params)

if isfield(arm_params,'theta')
    musc_end_1_x = [arm_params.X_gain*arm_params.r(1)*cos(arm_params.theta_ref(1))...
        arm_params.X_gain*arm_params.r(1)*cos(arm_params.theta_ref(1)+pi)...
        arm_params.X_e(1)-arm_params.r(1)*cos(arm_params.theta(:,1))...
        arm_params.X_e(1)+arm_params.r(1)*cos(arm_params.theta(:,1))];
    musc_end_1_y = [arm_params.r(1)*sin(arm_params.theta_ref(1))...
        arm_params.r(1)*sin(arm_params.theta_ref(1)+pi)...
        arm_params.X_e(2)-arm_params.r(1)*sin(arm_params.theta(:,1))...
        arm_params.X_e(2)+arm_params.r(1)*sin(arm_params.theta(:,1))];
    musc_end_2_x = [arm_params.r(1)*cos(arm_params.theta(:,1))...
        arm_params.r(1)*cos(arm_params.theta(:,1))...
        arm_params.X_e(1)+arm_params.r(1)*cos(arm_params.theta(:,2))...
        arm_params.X_e(1)+arm_params.r(1)*cos(arm_params.theta(:,2))];
    musc_end_2_y = [arm_params.r(1)*sin(arm_params.theta(:,1))...
        arm_params.r(1)*sin(arm_params.theta(:,1))...
        arm_params.X_e(2)+arm_params.r(1)*sin(arm_params.theta(:,2))...
        arm_params.X_e(2)+arm_params.r(1)*sin(arm_params.theta(:,2))];
    set(hFig.h_pect,'XData',[musc_end_1_x(1) musc_end_2_x(1)],'YData',[musc_end_1_y(1) musc_end_2_y(1)])
    set(hFig.h_del,'XData',[musc_end_1_x(2) musc_end_2_x(2)],'YData',[musc_end_1_y(2) musc_end_2_y(2)])
    set(hFig.h_bi,'XData',[musc_end_1_x(3) musc_end_2_x(3)],'YData',[musc_end_1_y(3) musc_end_2_y(3)])
    set(hFig.h_tri,'XData',[musc_end_1_x(4) musc_end_2_x(4)],'YData',[musc_end_1_y(4) musc_end_2_y(4)])
    
    set(hFig.h_la,'XData',[arm_params.X_s(1) arm_params.X_e(1)],'YData',[arm_params.X_s(2) arm_params.X_e(2)])
    set(hFig.h_ua,'XData',[arm_params.X_e(1) arm_params.X_h(1)],'YData',[arm_params.X_e(2) arm_params.X_h(2)])
%     set(hFig.h_la2,'XData',[0 arm_params.X_e2(1)],'YData',[0 arm_params.X_e2(2)])
%     set(hFig.h_ua2,'XData',[arm_params.X_e2(1) arm_params.X_h2(1)],'YData',[arm_params.X_e2(2) arm_params.X_h2(2)])
end
set(hFig.h_hand,'XData',arm_params.X_h(1),'YData',arm_params.X_h(2))
F_end = [arm_params.F_end(1) arm_params.F_end(2)];  
set(hFig.h_F,'XData',arm_params.X_h(1)+[0 .01*F_end(1)],'YData',arm_params.X_h(2)+[0 .01*F_end(2)])

set(hFig.h_Xreal,'XData',arm_params.X_hand_real(1),'YData',arm_params.X_hand_real(2))
set(hFig.h_Freal,'XData',arm_params.X_hand_real(1)+[0 .01*arm_params.F_end_real(1)],...
    'YData',arm_params.X_hand_real(2)+[0 .01*arm_params.F_end_real(2)])

set(hFig.h_text,'String',{['t = ' num2str(arm_params.t_now) ' s'];['k = ' num2str(arm_params.k(1))]})   
drawnow