%
% Parameters to obtain recruitment curves using h_m_recruitment_curve()
%
%       function h_m_params = h_m_recruitment_curve_default()
%
%       h_m_params              : structure with fields
%           stim_elecs          : 1-by-2 vector with stimulation electrode numbers (the return [positive phase first] element 2)
%           sync_out_elec       : sync out electrode number (to sync with cerebus)
%           min_stim_ampl       : minimum stimulation amplitude (mA)
%           max_stim_ampl       : maximum stimulation amplitude (mA)
%           stim_pw             : stimulation pulse width (ms)
%           nbr_steps           : nbr of stimulation amplitude steps
%           nbr_reps            : nbr stimuli delivered at each stimulation amplitude
%           beg_m_wave_win      : beginning of the window to calculate the M-wave. (ms) after the stimulus
%           end_m_wave_win      : end of the window to calculate the M-wave. (ms) after the stimulus
%           beg_h_reflex_win    : beginning of the window to calculate the H-reflex. (ms) after the stimulus
%           end_h_reflex_win    : end of the window to calculate the H-reflex. (ms) after the stimulus
%           beg_baseline_win    : beginning of the window to calculate the baseline EMG activity. (ms) after the stimulus
%           end_baseline_win    : end of the window to calculate the baseline EMG activity. (ms) after the stimulus
%           extra_rec_time      : recording time after the end of the h-reflex window. Used for data storage (ms) 
%           min_inter_stim_int  : minimum interval between consecutive stimuli (s)
%           max_inter_stim_int  : maximum interval between consecutive stimuli (s)
%           record_force_yn     : (=1) record force; (=0) don't
%           emg_ch_for_plot     : nbr EMG ch that will be plotted during the experiment
%           save_data_yn        : save Matlab and cerebus data
%           data_dir            : directory where the data will be saved
%           monkey              : monkey name, to generate the filename
%           task                : task name, to generate the filename
%           manual_stim_ctrl_yn : (=1) instead of waiting certain time between stimuli, the user hits enter to deliver the next stimulus




function h_m_params = h_m_recruitment_curve_default()



h_m_params  = struct(...
    'stim_elecs',               [1 2], ...
    'sync_out_elec',            32, ...
    'min_stim_ampl',            5, ...
    'max_stim_ampl',            10, ...
    'stim_pw',                  0.3, ...
    'nbr_steps',                10, ...
    'nbr_reps',                 1, ...
    'beg_m_wave_win',           2, ...
    'end_m_wave_win',           12, ...
    'beg_h_reflex_win',         12, ...
    'end_h_reflex_win',         22, ...
    'beg_baseline_win',         -20, ...
    'end_baseline_win',         0, ...
    'extra_rec_time',           100, ...
    'min_inter_stim_int',       5, ...
    'max_inter_stim_int',       5, ...
    'record_force_yn',          0, ...
    'emg_ch_for_plot',          1, ...
    'save_data_yn',             1, ...
    'data_dir',                 'c:\Users\limblab\Desktop\temp code', ...
    'monkey',                   'Jango', ...
    'task',                     'WF', ...
    'manual_stim_ctrl_yn',      1);
