%
% Parameters to obtain data to build stimulation to force models using
% stim_to_force_daq() 
%
%       function s_f_params = stim_to_force_daq_default()
%
%       s_f_params              : structure with fields
%           stim_elecs          : 1-by-2 vector with stimulation electrode numbers (the return [positive phase first] element 2)
%           stimulator_resolut  : step size (mA)
%           sync_out_elec       : sync out electrode number (to sync with cerebus)
%           min_stim_ampl       : minimum stimulation amplitude (mA)
%           max_stim_ampl       : maximum stimulation amplitude (mA)
%           stim_pw             : stimulation pulse width (ms)
%           stim_freq           : stimulation frequency (Hz)
%           train_duration      : stimulation train duration (ms)
%           nbr_steps           : nbr of stimulation amplitude steps
%           nbr_reps            : nbr stimuli delivered at each stimulation amplitude
%           min_inter_stim_int  : minimum interval between consecutive stimuli (s) (ISI is randomized)
%           max_inter_stim_int  : maximum interval between consecutive stimuli (s)
%           pre_stim_win        : time (ms), before the delivery of a stimulus, during which force will be recorded and plotted
%           post_stim_win       : time (ms), after the delivery of a stimulus, during which force will be recorded and plotted
%           ch_nbr_stim_trig_cb : analog channel to which the stimulator sync out is connected. Generates a 3 mA negative phase first
%                                   pulse every at the beginning of every stimulation train
%           save_data_yn        : save Matlab and Cerebus data
%           data_dir            : directory where the data will be saved
%           monkey              : monkey name, to generate the filename
%           task                : task name, to generate the filename
%           mono_or_diff        : monopolar or differential
%           
%           manual_stim_ctrl_yn : (=1) instead of waiting certain time between stimuli, the user hits enter to deliver the next stimulus
%



function s_f_params = stim_to_force_daq_default()



s_f_params  = struct(...
    'stim_elecs',               [16], ...
    'stimulator_resolut',       0.018, ...
    'sync_out_elec',            32, ...
    'min_stim_ampl',            4, ...
    'max_stim_ampl',            10, ...
    'stim_pw',                  0.3, ...
    'stim_freq',                30, ...
    'train_duration',           300, ...
    'nbr_steps',                10, ...
    'nbr_reps',                 4, ...
    'min_inter_stim_int',       4, ...
    'max_inter_stim_int',       10, ...
    'pre_stim_win',             500, ...
    'post_stim_win',            500, ...
    'ch_nbr_stim_trig_cb',      8, ...
    'save_data_yn',             1, ...
    'data_dir',                 'c:\Users\limblab\Desktop\temp code', ...
    'monkey',                   'Jango', ...
    'task',                     'WF', ...
    'mono_or_diff',             'mono', ...
    'muscle',                   'ECR-33-34', ...
    'manual_stim_ctrl_yn',      1);         
