%make electrode positions structure for neuronexus matrix array.

%initialize for Han area 3A array
depth_spacing=200;
shank_spacing=400;
bank_spacing=703;

%set values for 128chan array
e_pos =[     0     0     0;...
     0     2     0;...
     0     4     0;...
     0     6     0;...
     0     7     0;...
     0     5     0;...
     0     3     0;...
     0     1     0;...
     1     0     0;...
     1     2     0;...
     1     4     0;...
     1     6     0;...
     1     7     0;...
     1     5     0;...
     1     3     0;...
     2     0     0;...
     1     1     0;...
     2     6     0;...
     2     4     0;...
     2     2     0;...
     2     3     0;...
     2     5     0;...
     2     7     0;...
     3     2     0;...
     3     0     0;...
     2     1     0;...
     3     7     0;...
     3     6     0;...
     3     4     0;...
     3     1     0;...
     3     3     0;...
     3     5     0];
 
e_pos=[e_pos;e_pos;e_pos;e_pos];
e_pos(33:64,3)=1;
e_pos(65:96,3)=2;
e_pos(97:128,3)=3;

%load array into electrode_positions structure
electrode_positions.index =dataset({[1:128]','electrode'},{e_pos(:,1),'shank_num'},{e_pos(:,2),'depth_num'},{e_pos(:,3),'bank_num'});
electrode_positions.position=dataset({[1:128]','electrode'},{e_pos(:,1)*shank_spacing,'shank_pos'},{e_pos(:,2)*depth_spacing,'depth_pos'},{e_pos(:,3)*bank_spacing,'bank_pos'});

electrode_positions.units='um';
electrode_positions.depth_spacing=depth_spacing;
electrode_positions.shank_spacing=shank_spacing;
electrode_positions.bank_spacing=bank_spacing;













