function h1 = stimdaq_test_export()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
% 
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.



appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'uipanel', 18, ...
    'text', 68, ...
    'radiobutton', 2, ...
    'popupmenu', 7, ...
    'edit', 37, ...
    'pushbutton', 14, ...
    'slider', 2, ...
    'checkbox', 7, ...
    'axes', 4), ...
    'override', 1, ...
    'release', 13, ...
    'resize', 'none', ...
    'accessibility', 'on', ...
    'mfile', 0, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'template', '/Applications/MATLAB_R2009b.app/toolbox/matlab/guide/guitemplates/guidetemplate0.fig', ...
    'lastSavedFile', 'C:\Users\mkj605\Documents\control_code\stimdaq_test_export.m', ...
    'lastFilename', 'C:\Users\mkj605\Documents\MATLAB\stimdaq_test.fig');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'Units',get(0,'defaultfigureUnits'),...
'Position',[200 -89 1144 761],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',get(0,'defaultfigureColor'),...
'IntegerHandle',get(0,'defaultfigureIntegerHandle'),...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'MenuBar','none',...
'Name','stimdaq_test',...
'NumberTitle','off',...
'Resize','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'ScreenPixelsPerInchMode','manual',...
'Tag','figure1',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'forces_plot';

h2 = axes(...
'Parent',h1,...
'FontUnits',get(0,'defaultaxesFontUnits'),...
'Units','characters',...
'CameraMode',get(0,'defaultaxesCameraMode'),...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'CameraTarget',[0.5 0.5 0.5],...
'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
'CameraViewAngle',6.60861036031192,...
'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
'Position',[59 18.3846153846154 110.8 19.6923076923077],...
'ActivePositionProperty','position',...
'ActivePositionPropertyMode',get(0,'defaultaxesActivePositionPropertyMode'),...
'LooseInset',[12.376 4.41692307692308 9.044 3.01153846153846],...
'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
'PlotBoxAspectRatio',[1 0.462093862815884 0.462093862815884],...
'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
'XRulerMode',get(0,'defaultaxesXRulerMode'),...
'XTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
'XTickMode',get(0,'defaultaxesXTickMode'),...
'XTickLabel',{  '0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'; '1' },...
'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
'YRulerMode',get(0,'defaultaxesYRulerMode'),...
'YTick',[0 0.2 0.4 0.6 0.8 1],...
'YTickMode',get(0,'defaultaxesYTickMode'),...
'YTickLabel',{  '0'; '0.2'; '0.4'; '0.6'; '0.8'; '1' },...
'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
'ZRulerMode',get(0,'defaultaxesZRulerMode'),...
'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
'Color',get(0,'defaultaxesColor'),...
'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
'SortMethod','childorder',...
'SortMethodMode',get(0,'defaultaxesSortMethodMode'),...
'Tag','forces_plot',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h3 = get(h2,'title');

set(h3,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0.500000986381558 1.009765625 0.5],...
'PositionMode','auto',...
'String',blanks(0),...
'Interpreter','tex',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontSize',10,...
'FontAngle','normal',...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'LineStyle','-',...
'LineWidth',0.5,...
'BackgroundColor','none',...
'Margin',2,...
'Clipping','off',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'DisplayName',blanks(0),...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HelpTopicKey',blanks(0),...
'BusyAction','queue',...
'Interruptible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag',blanks(0),...
'UserData',[],...
'SelectionHighlight','on',...
'HitTest','on',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'Description','Axes Title',...
'DescriptionMode','auto',...
'Visible','on',...
'Serializable','on',...
'HandleVisibility','off',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

h4 = get(h2,'xlabel');

set(h4,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0.500000476837158 -0.0924479146876065 1.77635683940025e-15],...
'PositionMode','auto',...
'String',blanks(0),...
'Interpreter','tex',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontSize',10,...
'FontAngle','normal',...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','top',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'LineStyle','-',...
'LineWidth',0.5,...
'BackgroundColor','none',...
'Margin',2,...
'Clipping','off',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'DisplayName',blanks(0),...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HelpTopicKey',blanks(0),...
'BusyAction','queue',...
'Interruptible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag',blanks(0),...
'UserData',[],...
'SelectionHighlight','on',...
'HitTest','on',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','on',...
'Serializable','on',...
'HandleVisibility','off',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

h5 = get(h2,'ylabel');

set(h5,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[-0.0511431999405942 0.500000476837158 1.77635683940025e-15],...
'PositionMode','auto',...
'String',blanks(0),...
'Interpreter','tex',...
'Rotation',90,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontSize',10,...
'FontAngle','normal',...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'LineStyle','-',...
'LineWidth',0.5,...
'BackgroundColor','none',...
'Margin',2,...
'Clipping','off',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'DisplayName',blanks(0),...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HelpTopicKey',blanks(0),...
'BusyAction','queue',...
'Interruptible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag',blanks(0),...
'UserData',[],...
'SelectionHighlight','on',...
'HitTest','on',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','on',...
'Serializable','on',...
'HandleVisibility','off',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

h6 = get(h2,'zlabel');

set(h6,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0 0 0],...
'PositionMode','auto',...
'String',blanks(0),...
'Interpreter','tex',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontSize',10,...
'FontAngle','normal',...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','middle',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'LineStyle','-',...
'LineWidth',0.5,...
'BackgroundColor','none',...
'Margin',2,...
'Clipping','off',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'DisplayName',blanks(0),...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HelpTopicKey',blanks(0),...
'BusyAction','queue',...
'Interruptible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag',blanks(0),...
'UserData',[],...
'SelectionHighlight','on',...
'HitTest','on',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','off',...
'Serializable','on',...
'HandleVisibility','off',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

appdata = [];
appdata.lastValidTag = 'stim_plot';

h7 = axes(...
'Parent',h1,...
'FontUnits',get(0,'defaultaxesFontUnits'),...
'Units','characters',...
'CameraMode',get(0,'defaultaxesCameraMode'),...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'CameraTarget',[0.5 0.5 0.5],...
'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
'CameraViewAngle',6.60861036031192,...
'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
'Position',[59.2 2.23076923076923 110.6 13.3846153846154],...
'ActivePositionProperty','position',...
'ActivePositionPropertyMode',get(0,'defaultaxesActivePositionPropertyMode'),...
'LooseInset',[12.376 4.41692307692308 9.044 3.01153846153846],...
'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
'PlotBoxAspectRatio',[1 0.314647377938517 0.314647377938517],...
'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
'XRulerMode',get(0,'defaultaxesXRulerMode'),...
'XTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
'XTickMode',get(0,'defaultaxesXTickMode'),...
'XTickLabel',{  '0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'; '1' },...
'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
'YRulerMode',get(0,'defaultaxesYRulerMode'),...
'YTick',[0 0.2 0.4 0.6 0.8 1],...
'YTickMode',get(0,'defaultaxesYTickMode'),...
'YTickLabel',{  '0'; '0.2'; '0.4'; '0.6'; '0.8'; '1' },...
'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
'ZRulerMode',get(0,'defaultaxesZRulerMode'),...
'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
'Color',get(0,'defaultaxesColor'),...
'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
'SortMethod','childorder',...
'SortMethodMode',get(0,'defaultaxesSortMethodMode'),...
'Tag','stim_plot',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h8 = get(h7,'title');

set(h8,...
'Parent',h7,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0.500000989027524 1.01436781609195 0.499999999999996],...
'PositionMode','auto',...
'String',blanks(0),...
'Interpreter','tex',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontSize',10,...
'FontAngle','normal',...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'LineStyle','-',...
'LineWidth',0.5,...
'BackgroundColor','none',...
'Margin',2,...
'Clipping','off',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'DisplayName',blanks(0),...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HelpTopicKey',blanks(0),...
'BusyAction','queue',...
'Interruptible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag',blanks(0),...
'UserData',[],...
'SelectionHighlight','on',...
'HitTest','on',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'Description','Axes Title',...
'DescriptionMode','auto',...
'Visible','on',...
'Serializable','on',...
'HandleVisibility','off',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

h9 = get(h7,'xlabel');

set(h9,...
'Parent',h7,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0.500000476837158 -0.136015322758777 -1.77635683940025e-15],...
'PositionMode','auto',...
'String',blanks(0),...
'Interpreter','tex',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontSize',10,...
'FontAngle','normal',...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','top',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'LineStyle','-',...
'LineWidth',0.5,...
'BackgroundColor','none',...
'Margin',2,...
'Clipping','off',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'DisplayName',blanks(0),...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HelpTopicKey',blanks(0),...
'BusyAction','queue',...
'Interruptible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag',blanks(0),...
'UserData',[],...
'SelectionHighlight','on',...
'HitTest','on',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','on',...
'Serializable','on',...
'HandleVisibility','off',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

h10 = get(h7,'ylabel');

set(h10,...
'Parent',h7,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[-0.0512356831231269 0.500000476837158 -1.77635683940025e-15],...
'PositionMode','auto',...
'String',blanks(0),...
'Interpreter','tex',...
'Rotation',90,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontSize',10,...
'FontAngle','normal',...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'LineStyle','-',...
'LineWidth',0.5,...
'BackgroundColor','none',...
'Margin',2,...
'Clipping','off',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'DisplayName',blanks(0),...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HelpTopicKey',blanks(0),...
'BusyAction','queue',...
'Interruptible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag',blanks(0),...
'UserData',[],...
'SelectionHighlight','on',...
'HitTest','on',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','on',...
'Serializable','on',...
'HandleVisibility','off',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

h11 = get(h7,'zlabel');

set(h11,...
'Parent',h7,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0 0 0],...
'PositionMode','auto',...
'String',blanks(0),...
'Interpreter','tex',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontSize',10,...
'FontAngle','normal',...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','middle',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'LineStyle','-',...
'LineWidth',0.5,...
'BackgroundColor','none',...
'Margin',2,...
'Clipping','off',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'DisplayName',blanks(0),...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HelpTopicKey',blanks(0),...
'BusyAction','queue',...
'Interruptible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag',blanks(0),...
'UserData',[],...
'SelectionHighlight','on',...
'HitTest','on',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','off',...
'Serializable','on',...
'HandleVisibility','off',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

appdata = [];
appdata.lastValidTag = 'force_vec_plot';

h12 = axes(...
'Parent',h1,...
'FontUnits',get(0,'defaultaxesFontUnits'),...
'Units','characters',...
'CameraMode',get(0,'defaultaxesCameraMode'),...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'CameraTarget',[0.5 0.5 0.5],...
'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
'CameraViewAngle',6.60861036031192,...
'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
'Position',[10 2.30769230769231 40 13.3846153846154],...
'ActivePositionProperty','position',...
'ActivePositionPropertyMode',get(0,'defaultaxesActivePositionPropertyMode'),...
'LooseInset',[12.376 4.41692307692308 9.044 3.01153846153846],...
'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
'PlotBoxAspectRatio',[1 0.87 0.87],...
'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
'XRulerMode',get(0,'defaultaxesXRulerMode'),...
'XTick',[0 0.5 1],...
'XTickMode',get(0,'defaultaxesXTickMode'),...
'XTickLabel',{  '0'; '0.5'; '1' },...
'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
'YRulerMode',get(0,'defaultaxesYRulerMode'),...
'YTick',[0 0.2 0.4 0.6 0.8 1],...
'YTickMode',get(0,'defaultaxesYTickMode'),...
'YTickLabel',{  '0'; '0.2'; '0.4'; '0.6'; '0.8'; '1' },...
'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
'ZRulerMode',get(0,'defaultaxesZRulerMode'),...
'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
'Color',get(0,'defaultaxesColor'),...
'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
'SortMethod','childorder',...
'SortMethodMode',get(0,'defaultaxesSortMethodMode'),...
'Tag','force_vec_plot',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h13 = get(h12,'title');

set(h13,...
'Parent',h12,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0.500000720024109 1.01436781609195 0.499999999999998],...
'PositionMode','auto',...
'String',blanks(0),...
'Interpreter','tex',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontSize',10,...
'FontAngle','normal',...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'LineStyle','-',...
'LineWidth',0.5,...
'BackgroundColor','none',...
'Margin',2,...
'Clipping','off',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'DisplayName',blanks(0),...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HelpTopicKey',blanks(0),...
'BusyAction','queue',...
'Interruptible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag',blanks(0),...
'UserData',[],...
'SelectionHighlight','on',...
'HitTest','on',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'Description','Axes Title',...
'DescriptionMode','auto',...
'Visible','on',...
'Serializable','on',...
'HandleVisibility','off',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

h14 = get(h12,'xlabel');

set(h14,...
'Parent',h12,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0.500000476837158 -0.136015322758777 0],...
'PositionMode','auto',...
'String',blanks(0),...
'Interpreter','tex',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontSize',10,...
'FontAngle','normal',...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','top',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'LineStyle','-',...
'LineWidth',0.5,...
'BackgroundColor','none',...
'Margin',2,...
'Clipping','off',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'DisplayName',blanks(0),...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HelpTopicKey',blanks(0),...
'BusyAction','queue',...
'Interruptible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag',blanks(0),...
'UserData',[],...
'SelectionHighlight','on',...
'HitTest','on',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','on',...
'Serializable','on',...
'HandleVisibility','off',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

h15 = get(h12,'ylabel');

set(h15,...
'Parent',h12,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[-0.141666663835446 0.500000476837158 0],...
'PositionMode','auto',...
'String',blanks(0),...
'Interpreter','tex',...
'Rotation',90,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontSize',10,...
'FontAngle','normal',...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'LineStyle','-',...
'LineWidth',0.5,...
'BackgroundColor','none',...
'Margin',2,...
'Clipping','off',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'DisplayName',blanks(0),...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HelpTopicKey',blanks(0),...
'BusyAction','queue',...
'Interruptible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag',blanks(0),...
'UserData',[],...
'SelectionHighlight','on',...
'HitTest','on',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','on',...
'Serializable','on',...
'HandleVisibility','off',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

h16 = get(h12,'zlabel');

set(h16,...
'Parent',h12,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0 0 0],...
'PositionMode','auto',...
'String',blanks(0),...
'Interpreter','tex',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontSize',10,...
'FontAngle','normal',...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','middle',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'LineStyle','-',...
'LineWidth',0.5,...
'BackgroundColor','none',...
'Margin',2,...
'Clipping','off',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'DisplayName',blanks(0),...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HelpTopicKey',blanks(0),...
'BusyAction','queue',...
'Interruptible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag',blanks(0),...
'UserData',[],...
'SelectionHighlight','on',...
'HitTest','on',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','off',...
'Serializable','on',...
'HandleVisibility','off',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

appdata = [];
appdata.lastValidTag = 'modulation_panel';

h17 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','pixels',...
'Title','Modulation Control',...
'Position',[378 552 225 199],...
'Clipping','off',...
'ChildrenMode','manual',...
'Tag','modulation_panel',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'modulation_mode_menu';

h18 = uicontrol(...
'Parent',h17,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',{  'Single Pulses'; 'Train'; 'Pulse-width Modulation '; 'Amplitude Modulation '; blanks(0); blanks(0) },...
'Style','popupmenu',...
'Value',1,...
'Position',[11.8 12.1538461538462 31.6 1.53846153846154],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'ParentMode','manual',...
'Tag','modulation_mode_menu',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text2';

h19 = uicontrol(...
'Parent',h17,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Mode:',...
'Style','text',...
'Position',[3.8 12.3076923076923 6.2 1.15384615384615],...
'Children',[],...
'Tag','text2',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'multiplier_controls_panel';

h20 = uipanel(...
'Parent',h17,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'BorderType','none',...
'Title',blanks(0),...
'Position',[1 0.538461538461539 41.8 11.4615384615385],...
'Clipping','off',...
'Tag','multiplier_controls_panel',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'multiplier_max_text';

h21 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Multiplier Maximum',...
'Style','text',...
'Position',[10 92.9999999999999 92 15],...
'Children',[],...
'Tag','multiplier_max_text',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'multiplier_min';

h22 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','0.1',...
'Style','edit',...
'Value',0.1,...
'Position',[105 120 50 19],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','multiplier_min',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'multiplier_max';

h23 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','1.0',...
'Style','edit',...
'Value',1,...
'Position',[105 90.9999999999999 50 19],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','multiplier_max',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'multiplier_delta';

h24 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','0.1',...
'Style','edit',...
'Value',0.1,...
'Position',[105 58.9999999999999 49 22],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','multiplier_delta',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'multiplier_delta_text';

h25 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Multiplier Delta',...
'Style','text',...
'Position',[10 63.9999999999999 71 15],...
'Children',[],...
'Tag','multiplier_delta_text',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pulse_min_button';

h26 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Pulse',...
'Position',[165 120 41 19],...
'Children',[],...
'Tag','pulse_min_button',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pulse_max_button';

h27 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Pulse',...
'Position',[165 90.9999999999999 41 19],...
'Children',[],...
'Tag','pulse_max_button',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'multiplier_min_text';

h28 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Multiplier Minimum',...
'Style','text',...
'Position',[10 122 88 15],...
'Children',[],...
'Tag','multiplier_min_text',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text62';

h29 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Integration Window for Modulation',...
'Style','text',...
'Position',[16 36 172 15],...
'Children',[],...
'Tag','text62',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text63';

h30 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','ms',...
'Style','text',...
'Position',[122 10 21 15],...
'Children',[],...
'Tag','text63',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text64';

h31 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','to',...
'Style','text',...
'Position',[70 13 21 15],...
'Children',[],...
'Tag','text64',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'mod_window_1';

h32 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','350',...
'Style','edit',...
'Value',350,...
'Position',[38 10 31 21],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','mod_window_1',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'mod_window_2';

h33 = uicontrol(...
'Parent',h20,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','550',...
'Style','edit',...
'Value',550,...
'Position',[93 10 31 21],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','mod_window_2',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'stim_param_panel';

h34 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','pixels',...
'Title','Stimulation Parameters',...
'Position',[6 250 214 501],...
'Clipping','off',...
'Tag','stim_param_panel',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text8';

h35 = uicontrol(...
'Parent',h34,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Frequency',...
'Style','text',...
'Position',[20 463 53 15],...
'Children',[],...
'Tag','text8',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'stim_freq';

h36 = uicontrol(...
'Parent',h34,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','50',...
'Style','edit',...
'Value',50,...
'Position',[80 461 51 19],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','stim_freq',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text9';

h37 = uicontrol(...
'Parent',h34,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Hz',...
'Style','text',...
'Position',[140 463 13 15],...
'Children',[],...
'Tag','text9',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text10';

h38 = uicontrol(...
'Parent',h34,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Pulses',...
'Style','text',...
'Position',[20 438 53 15],...
'Children',[],...
'Tag','text10',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'stim_pulses';

h39 = uicontrol(...
'Parent',h34,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','25',...
'Style','edit',...
'Value',25,...
'Position',[80 436 51 19],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','stim_pulses',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text12';

h40 = uicontrol(...
'Parent',h34,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',{  'Parameter Table'; 'Created Programmatically' },...
'Style','text',...
'Position',[3.8 18 31.4 2.76923076923077],...
'Children',[],...
'ForegroundColor',[0.392156862745098 0.392156862745098 0.392156862745098],...
'Visible','off',...
'Tag','text12',...
'FontSize',10,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text37';

h41 = uicontrol(...
'Parent',h34,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','mA',...
'Style','text',...
'Position',[6 0.230769230769231 10.4 1.07692307692308],...
'Children',[],...
'Tag','text37',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text38';

h42 = uicontrol(...
'Parent',h34,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','msec',...
'Style','text',...
'Position',[18.2 0.230769230769231 10.4 1.07692307692308],...
'Children',[],...
'Tag','text38',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'start_button';

h43 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Start',...
'Style','togglebutton',...
'Position',[427 523 60 22],...
'Children',[],...
'Tag','start_button',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'abort_button';

h44 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Abort',...
'Position',[493 523 60 22],...
'Children',[],...
'Tag','abort_button',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'loaded_data_panel';

h45 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Loaded Data',...
'Position',[121.4 42.3846153846154 47.6 15.3846153846154],...
'Clipping','off',...
'Tag','loaded_data_panel',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'save_button';

h46 = uicontrol(...
'Parent',h45,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Save As...',...
'Position',[10 138 61 22],...
'Children',[],...
'Tag','save_button',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'save_status_text';

h47 = uicontrol(...
'Parent',h45,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String',blanks(0),...
'Style','text',...
'Position',[80 135 151 21],...
'Children',[],...
'Tag','save_status_text',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'loaded_data_subpanel';

h48 = uipanel(...
'Parent',h45,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','pixels',...
'Title','Plotting',...
'Position',[6 8 226 129],...
'Clipping','off',...
'ChildrenMode','manual',...
'Tag','loaded_data_subpanel',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'plot_raw_data_button';

h49 = uicontrol(...
'Parent',h48,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Raw Data',...
'Position',[10 85 84 21],...
'Children',[],...
'Tag','plot_raw_data_button',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'plot_raw_data_menu';

h50 = uicontrol(...
'Parent',h48,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  'Channel 1'; 'Channel 2'; 'Channel 3'; 'Channel 4'; 'Channel 5'; 'Channel 6'; 'Channel 7'; 'Channel 8' },...
'Style','popupmenu',...
'Value',1,...
'Position',[107 85 96 21],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'ParentMode','manual',...
'Tag','plot_raw_data_menu',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text19';

h51 = uicontrol(...
'Parent',h48,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Integration window',...
'Style','text',...
'Position',[107 35 97 15],...
'Children',[],...
'Tag','text19',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text21';

h52 = uicontrol(...
'Parent',h48,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','ms',...
'Style','text',...
'Position',[191 13 21 15],...
'Children',[],...
'Tag','text21',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text20';

h53 = uicontrol(...
'Parent',h48,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','to',...
'Style','text',...
'Position',[138 13 21 15],...
'Children',[],...
'Tag','text20',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'plot_recruitments_button';

h54 = uicontrol(...
'Parent',h48,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Recruit Curves',...
'Position',[12 10 84 21],...
'Children',[],...
'Tag','plot_recruitments_button',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'recruit_window_min';

h55 = uicontrol(...
'Parent',h48,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','350',...
'Style','edit',...
'Value',350,...
'Position',[107 10 31 21],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','recruit_window_min',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'recruit_window_max';

h56 = uicontrol(...
'Parent',h48,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','550',...
'Style','edit',...
'Value',550,...
'Position',[158 10 31 21],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','recruit_window_max',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'mle_fit_chbx';

h57 = uicontrol(...
'Parent',h48,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','MLE fit (Default: nonlin lstsqrs)',...
'Style','checkbox',...
'Position',[3.4 4 36.2 1.76923076923077],...
'Children',[],...
'Tag','mle_fit_chbx',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text15';

h58 = uicontrol(...
'Parent',h45,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Recorded at:',...
'Style','text',...
'Position',[10 165 65 15],...
'Children',[],...
'Tag','text15',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'recording_time_text';

h59 = uicontrol(...
'Parent',h45,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String',blanks(0),...
'Style','text',...
'Position',[74 165 50 15],...
'Children',[],...
'Tag','recording_time_text',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text17';

h60 = uicontrol(...
'Parent',h45,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Mode:',...
'Style','text',...
'Position',[25.8 12.6153846153846 6.2 1.15384615384615],...
'Children',[],...
'Tag','text17',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'mode_text';

h61 = uicontrol(...
'Parent',h45,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String',blanks(0),...
'Style','text',...
'Position',[160 165 60 15],...
'Children',[],...
'Tag','mode_text',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'total_pulse_count';

h62 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'String','1',...
'Style','text',...
'Position',[559 527 25 15],...
'Children',[],...
'Tag','total_pulse_count',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text6';

h63 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Stimulation(s) per params',...
'Style','text',...
'Position',[589 527 129 15],...
'Children',[],...
'Tag','text6',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel13';

h64 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Additional Parameters',...
'Position',[43.8000000000002 42.3846153846154 31.8 15.3076923076923],...
'Clipping','off',...
'Tag','uipanel13',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text29';

h65 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','DAQ Freq',...
'Style','text',...
'Position',[17 159 53 15],...
'Children',[],...
'Tag','text29',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'daq_freq';

h66 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','1000',...
'Style','edit',...
'Value',1000,...
'Position',[81 156 51 19],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','daq_freq',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text30';

h67 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Hz',...
'Style','text',...
'Position',[132 157 13 15],...
'Children',[],...
'Tag','text30',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text31';

h68 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Stim Reps',...
'Style','text',...
'Position',[17 123 53 15],...
'Children',[],...
'Tag','text31',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'stim_reps';

h69 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','1',...
'Style','edit',...
'Value',1,...
'Position',[81 120 51 19],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','stim_reps',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text32';

h70 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Interphase',...
'Style','text',...
'Position',[17 98.9999999999999 53 15],...
'Children',[],...
'Tag','text32',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'stim_interphase';

h71 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','0.5',...
'Style','edit',...
'Value',0.5,...
'Position',[81 95.9999999999999 51 19],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','stim_interphase',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text33';

h72 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','mS',...
'Style','text',...
'Position',[131 97.9999999999999 22 15],...
'Children',[],...
'Tag','text33',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'EMG_labels_button';

h73 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Define EMGs & ATI',...
'Position',[5.4 0.692307692307686 22.6 1.76923076923077],...
'Children',[],...
'Tag','EMG_labels_button',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text26';

h74 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','ms',...
'Style','text',...
'Position',[121 72.9999999999999 21 15],...
'Children',[],...
'Tag','text26',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text27';

h75 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Record for:',...
'Style','text',...
'Position',[23 71.9999999999999 57 17],...
'Children',[],...
'Tag','text27',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'rec_duration';

h76 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','2500',...
'Style','edit',...
'Value',2500,...
'Position',[81 69.9999999999999 37 21],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','rec_duration',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text34';

h77 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Stim Delay ',...
'Style','text',...
'Position',[17 48 53 15],...
'Children',[],...
'Tag','text34',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'stim_delay';

h78 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','60',...
'Style','edit',...
'Value',60,...
'Position',[81 44.9999999999999 36 19],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','stim_delay',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text35';

h79 = uicontrol(...
'Parent',h64,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','sec',...
'Style','text',...
'Position',[122 44.9999999999999 21 15],...
'Children',[],...
'Tag','text35',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text40';

h80 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Notes:',...
'Style','text',...
'Position',[182 15.8461538461538 27.2 1.53846153846154],...
'Children',[],...
'Tag','text40',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text41';

h81 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',{  'save new calibration matrix'; 'costim only inverts pulseAMP-force recruit'; 'MVC averaged over last 2 trials in plot function'; blanks(0) },...
'Style','text',...
'Position',[182 9.92307692307692 27.2 6.15384615384615],...
'Children',[],...
'Tag','text41',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text44';

h82 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Current action:',...
'Style','text',...
'Position',[912 93 120 22],...
'Children',[],...
'Tag','text44',...
'FontSize',12,...
'FontWeight','bold',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel14';

h83 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'ForegroundColor',[1 0 0],...
'ShadowColor',[1 0 0],...
'BorderWidth',3,...
'Title','action panel',...
'Position',[179.8 3.23076923076923 29.2 6.76923076923077],...
'Clipping','off',...
'Tag','uipanel14',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'curr_action_text';

h84 = uicontrol(...
'Parent',h83,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String',blanks(0),...
'Style','text',...
'Position',[10 7.99999999999997 126 38],...
'Children',[],...
'Tag','curr_action_text',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'optimalctrl_panel';

h85 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Optimal Control',...
'Position',[174.8 32.6153846153846 45 25.3076923076923],...
'Clipping','off',...
'Tag','optimalctrl_panel',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'optctrl_panel';

h86 = uipanel(...
'Parent',h85,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'BorderType','none',...
'Title',blanks(0),...
'Position',[1 0.846153846153846 43 21.0769230769231],...
'Clipping','off',...
'ChildrenMode','manual',...
'Tag','optctrl_panel',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text52';

h87 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','# ctrl pts:',...
'Style','text',...
'Position',[19 228 53 15],...
'Children',[],...
'Tag','text52',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'optctrl_numpts';

h88 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','5',...
'Style','edit',...
'Value',5,...
'Position',[71 226 20 19],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','optctrl_numpts',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'autoCtrl';

h89 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','auto select desired forces',...
'Style','checkbox',...
'Position',[4.4 13.3076923076923 32 1.76923076923077],...
'Children',[],...
'Tag','autoCtrl',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text55';

h90 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','# reps:',...
'Style','text',...
'Position',[33 203 40 15],...
'Children',[],...
'Tag','text55',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'optctrl_numreps';

h91 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','1',...
'Style','edit',...
'Value',1,...
'Position',[72 201 20 19],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','optctrl_numreps',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text56';

h92 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Integration Window',...
'Style','text',...
'Position',[37 155 107 15],...
'Children',[],...
'Tag','text56',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text57';

h93 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','ms',...
'Style','text',...
'Position',[125 129 21 15],...
'Children',[],...
'Tag','text57',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text58';

h94 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','to',...
'Style','text',...
'Position',[73 132 21 15],...
'Children',[],...
'Tag','text58',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'tw_optctrl_low';

h95 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','350',...
'Style','edit',...
'Value',350,...
'Position',[41 129 31 21],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','tw_optctrl_low',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'tw_optctrl_hi';

h96 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','550',...
'Style','edit',...
'Value',550,...
'Position',[96 129 31 21],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','tw_optctrl_hi',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text59';

h97 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','% FFS:',...
'Style','text',...
'Position',[114 227 36 15],...
'Children',[],...
'Tag','text59',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'level_act_optctrl';

h98 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','75',...
'Style','edit',...
'Value',75,...
'Position',[149 227 20 19],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','level_act_optctrl',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'stagger_stim';

h99 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','stagger',...
'Style','checkbox',...
'Position',[3.6 19.2307692307692 17.8 1.76923076923077],...
'Children',[],...
'Tag','stagger_stim',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text61';

h100 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','ms',...
'Style','text',...
'Position',[114 255 21 15],...
'Children',[],...
'Tag','text61',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'stagger_stim_time';

h101 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','100',...
'Style','edit',...
'Value',60,...
'Position',[77 253 36 19],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','stagger_stim_time',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'optctrl_mode_menu';

h102 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',{  'Force Magnitude'; 'Independent Fx Fy'; 'Sampling Force Mag' },...
'Style','popupmenu',...
'Value',1,...
'Position',[9 7.15384615384615 30.6 1.53846153846154],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'ParentMode','manual',...
'Tag','optctrl_mode_menu',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text65';

h103 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Mode:',...
'Style','text',...
'Position',[2 7.30769230769231 6.2 1.15384615384615],...
'Children',[],...
'Tag','text65',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'cost_r';

h104 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','10',...
'Style','edit',...
'Value',10,...
'Position',[79 54 31 20],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','cost_r',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'cost_q';

h105 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','1e6',...
'Style','edit',...
'Value',1000000,...
'Position',[79 24 31 21],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','cost_q',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'cost_rn';

h106 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','R',...
'Style','text',...
'Position',[56 57 21 15],...
'Children',[],...
'Tag','cost_rn',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'cost_qn';

h107 = uicontrol(...
'Parent',h86,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Q',...
'Style','text',...
'Position',[56 27 21 15],...
'Children',[],...
'Tag','cost_qn',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'optctrl_active';

h108 = uicontrol(...
'Parent',h85,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','opt ctrl active',...
'Style','checkbox',...
'Position',[4.8 21.9230769230769 19 1.76923076923077],...
'Children',[],...
'Tag','optctrl_active',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'figclose';

h109 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Close Figures',...
'Position',[940 327 81 22],...
'Children',[],...
'Tag','figclose',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'maria35';

h110 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','maria345',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[44.8 39.2307692307692 22.4 2.07692307692308],...
'Callback','maria',...
'Children',[],...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, 'maria23', appdata} ,...
'Tag','maria35');



% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end
