function savecds(cds,filePath)
    %savecds is a method of the cds class, and should be saved in the
    %@commonDataStructure folder
    %
    %savecds(filePath) converts the cds to a structure and saves it in a 
    %file with the name given by filePath
    
%     saveStruct=struct(  'meta',cds.meta,...
%                         'kinFilterConfig',cds.kinFilterConfig,...
%                         'kin',cds.kin,...
%                         'force',cds.force,...
%                         'lfp',cds.lfp,...
%                         'emg',cds.emg,...
%                         'analog',cds.analog,...
%                         'triggers',cds.triggers,...
%                         'units',cds.units,...
%                         'trials',cds.trials);
    save(filePath,'cds')
    
end